### ISSUE TITLE
Static IP does not work

### ISSUE THREAD

**Issue by TFhdKi95ae8L** [rstrouse/ESPSomfy-RTS#100]
First off, very nice project! Works flawlessly.

Due to issues with my router, I'd like to set a static IP address in the ESP itself.
It does not work however...
Using V2.0.0, and rebooting after unticking DHCP and modifying the IP does not make the ESP change IP, it keeps the old one.

If you need any info, please let me know.

**Comment by rstrouse** [comment]
Install this firmware file (you do not need the littlefs.bin file) and let me know if it persists your IP address.

https://github.com/rstrouse/ESPSomfy-RTS/blob/main/SomfyController.ino.esp32.bin

**Comment by TFhdKi95ae8L** [comment]
Works!
Good fix.
