### ISSUE TITLE
use longer MQTT-host-url

### ISSUE THREAD

**Issue by tschnilo** [rstrouse/ESPSomfy-RTS#103]
Hi,

i want to use a public MQTT-broker with an long host-url (about 55 signs). I was able to set and save the mqtt-host-url at the UI. But after rebooting the esp the url was cut off at 31 signs and no mqtt-messages arrives the broker.
Is it possible to make the mqtt-client working with longer urls.

**Comment by rstrouse** [comment]
I'll have a look and see where I am at for storage space in nvs.

**Comment by rstrouse** [comment]
v2.0.1 increases the length to 64 characters.

**Comment by tschnilo** [comment]
Fixed
