### ISSUE TITLE
Incorrect syntax on "groupCommand" REST command?

### ISSUE THREAD

**Issue by KartmanCanada** [rstrouse/ESPSomfy-RTS#105]
on v2.0.0

This works: http://192.168.0.203:8081/shadeCommand?shadeId=1&command=down

This doesn't: http://192.168.0.203:8081/groupCommand?groupId=1&command=down
--> returns: {"status":"ERROR","desc":"No group object supplied."}

Group has been created and functions correctly when initiating movement via ESPSomfy web interface. Any ideas?

Many thanks.

**Comment by rstrouse** [comment]
Funny there was a typo on the route.  Update to v2.0.2 and your problems will disappear into the ether.  At least the ones related to this issue.

**Comment by KartmanCanada** [comment]
Confirmed Fixed.
