### ISSUE TITLE
Nothing in the logs - SPI is working fine.

### ISSUE THREAD

**Issue by steveomg** [rstrouse/ESPSomfy-RTS#106]
Having the same issue as in this previous closed topic.  Verfied wiring, rx frequency 250, tried multiple hardware.  Any other tips or hints?

_Originally posted by @steveomg in https://github.com/rstrouse/ESPSomfy-RTS/issues/51#issuecomment-1642923391_

**Comment by rstrouse** [comment]
Look at your remote.  Is this an RTS remote or an IO remote.  This project is for RTS remotes.

**Comment by steveomg** [comment]
Says RTS.  

Going to order new antennas.  I think these $2 for 2 are not working.

**Comment by rstrouse** [comment]
> Says RTS
Awesome I was hoping it was not IO.


Lets also look at your RX and TX wiring.  Can you shoot a couple of pics.  If there is no center pin in the antenna (female) then it is an RP-SMA antenna and will not work.  Also if it is tuned for some frequency other than 433MHz then it is good as a tickle stick but nothing else.

**Comment by steveomg** [comment]
RX and TX are valid.  I have verified 100 times and also swapped at least that many times. I am about to order more antennas and will give that a whirl.

**Comment by rstrouse** [comment]
Make sure you order SMA (not RP-SMA) antennas tuned to 433MHz.

BTW: A tickle stick is used to coerce gulf lobster out of their holes.

**Comment by steveomg** [comment]
Grabbed this one
NOYITO 433MHz Antenna 5dBi Gain Omnidirectional Antenna 430-470MHz SMA Connector - Internal Thread Inner Needle https://a.co/d/5ZiNJxX

More used to swamp lobsters over here.

**Comment by rstrouse** [comment]
Mud bugs.  Delicious. 

That looks like a fine antenna according to the specs.   Normally the transceiver should pick up some signal with the remote next to it.   Try setting your RX and TX in the config to the same pin.   Don’t change your wiring just set them both to where the GDO0 is connected to.

**Comment by steveomg** [comment]
Antenna was the issue.  This one is working fine, though not quite 'tuned'.
