### ISSUE TITLE
Question:  adding  sunFlag  to blind?

### ISSUE THREAD

**Issue by wutz-ESP** [rstrouse/ESPSomfy-RTS#107]
Is ist possible adding sunFlag to blind or create blind+tilt+sun ?

my configuration
awning - sunFlag      activ / inactiv
blind - no sunFlag    no sunFlag

blind is using J4 RTS wich can be used together with sun/wind-sensor

find in somfy.cpp line 1141

> else if (this->shadeType == shade_types::awning) {
      const uint8_t sunFlag = !!(this->flags & static_cast<uint8_t>(somfy_flags_t::SunFlag));
      const uint8_t isSunny = !!(this->flags & static_cast<uint8_t>(somfy_flags_t::Sunny));
      const uint8_t isWindy = !!(this->flags & static_cast<uint8_t>(somfy_flags_t::Windy));

      snprintf(topic, sizeof(topic), "shades/%u/sunFlag", this->shadeId);
      mqtt.publish(topic, sunFlag);
      snprintf(topic, sizeof(topic), "shades/%u/sunny", this->shadeId);
      mqtt.publish(topic, isSunny);
      snprintf(topic, sizeof(topic), "shades/%u/windy", this->shadeId);
      mqtt.publish(topic, isWindy);
    }

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/110094334/b43ae3a9-9308-4b7e-8853-0dd4453b885d)

**Comment by rstrouse** [comment]
In the next update I will add the ability to configure sun sensors for all motors.

**Comment by rstrouse** [comment]
v2.1.0 contains this functionality.  Do not forget to update your ESPSomfy RTS-HA home assistant component.  It will also add the appropriate sensors and controls for the sun/wind sensor.
