### ISSUE TITLE
Can't login by password

### ISSUE THREAD

**Issue by blastrock** [rstrouse/ESPSomfy-RTS#108]
I have set up the password authentication on espsomfyrts, but I can't get past the login form.

Looking at the code, it goes through some PIN specific code:

```js
        let pin = '';
        for (let i = 0; i < 4; i++) {
            pin += sec.pin[`d${i}`];
        }
        if (pin.length !== 4) return;
```

`pin.length` is 0 there, so nothing happens when I click login.

**Comment by 011V32** [comment]
I have the same problem :(

**Comment by rstrouse** [comment]
Uggh.  This plugged a ui error and painted into the corner.

Please run the following url from your browser.
`http://<ip address of espsomfyrts>/backup`

And save this file.  I am rebuilding an onboard file now.

**Comment by blastrock** [comment]
As a workaround, commenting the `if (pin.length !== 4)` line in the dev console allows me to log in :)

**Comment by rstrouse** [comment]
That works too!

**Comment by rstrouse** [comment]
v2.0.3 no longer has this issue.

**Comment by 011V32** [comment]
I can confirm that it now works. 👍

I would have 2 suggestions for improvement:
1. It would be great if a key-enter would also work for login. (Currently you can only get in if you press the login button with the mouse).
2. When you reload the page you should stay logged in. Currently you are logged out after each refresh.

**Comment by rstrouse** [comment]
v2.1.0 will process the enter key.  ESPSomfy RTS cannot maintain a session with the device.  The webserver on ESP32 is definitely not that robust.  A cookie could store the key hash locally but that creates even more headaches.

**Comment by rstrouse** [comment]
v2.1.0 has been released.

**Comment by 011V32** [comment]
The "normal" Enter works, but the enter from the Num-Block doesn't 🙈

**Comment by rstrouse** [comment]
Hmmm different keyboard mapping.  Uggh.
