### ISSUE TITLE
TX Power not saving after a reboot

### ISSUE THREAD

**Issue by prbtt** [rstrouse/ESPSomfy-RTS#11]
Apparently whenever you change the TX Power, it resets back to 10 dB after a reboot. I'm running the latest version.

**Comment by rstrouse** [comment]
I will be posting a new version soon that fixes this issue.

**Comment by rstrouse** [comment]
Release v1.4.4 fixes this issue and has been published.

**Comment by rstrouse** [comment]
I think we have this solved for now as I found the place where I missed persisting it to NVS.  Open another issue if you see this again or re-open this one.
