### ISSUE TITLE
Backup of all settings

### ISSUE THREAD

**Issue by 011V32** [rstrouse/ESPSomfy-RTS#110]
enhancement

Hello.

It would be great if all settings could be saved in the backup.
So not only those of somfy (shades/groups), but also those of the system, network, radio, ...
Thank you.

Regards

**Comment by rstrouse** [comment]
This one is kind of dicey.  Indiscriminately changing the pin assignments especially with an ethernet board can prove to be bad news.  Incorrect settings on the PHY can destroy the board.  Also, importing network settings after having hooked up your network might prove to be a bit annoying.  

Timezones, mqtt, and even frequency/protocol settings are pretty innocuous so maybe there is a balance.

**Comment by 011V32** [comment]
How about a dialog where you can then select what can be restored?
(The "enable radio" needn't be set.)

**Comment by rstrouse** [comment]
New functionality for backup and restore coming in the 2.1.6 release.

https://github.com/rstrouse/ESPSomfy-RTS/wiki/Configuring-the-Software#backup-and-restore

**Comment by rstrouse** [comment]
v2.1.6 has been released and has the ability to backup and restore nearly all of the settings.  Any potential security items are not contained in the backup file.
