### ISSUE TITLE
Preselection of the IO pin configuration

### ISSUE THREAD

**Issue by 011V32** [rstrouse/ESPSomfy-RTS#111]
enhancement

Hello.

It would be great if the IO pin configuration would not only have the manual configuration, but also above a dropdown where you can select the "usual" (which you had in your documentation) configurations.
If then a configuration is selected, then the IO pins should still be displayed, but grayed out and can not be changed. Only in the setting "Manual" (this is probably the default setting that it is compatible) the IOs should then be able to be adjusted manually.
What do you think of this suggestion?
(This would save time in the steup and avoid errors).
Thx.

Regards

**Comment by rstrouse** [comment]
I am not going to do this as I think I am just as likely to have the wrong settings.  The number one issue faced is that folks do not follow the recommended installation, then don't get the pins correctly configured.
