### ISSUE TITLE
MQTT Port will not be saved

### ISSUE THREAD

**Issue by Kami0612** [rstrouse/ESPSomfy-RTS#12]
I need Port 1884, but i see no commuincation.
After rebooting there is always Port 1883, although I typed and saved port 1884.

**Comment by rstrouse** [comment]
Thanks I will post an update shortly.  It looks like I never parsed port data out before persisting it.

**Comment by Kami0612** [comment]
Thanks, now ist works.
Firmware 1.4.4 and Application 1.4.5  ist okay?

**Comment by rstrouse** [comment]
Yes that is fine.  The only difference is that I did not stamp the binary.
