### ISSUE TITLE
Radio activated but no signal is being picked up, no RSSI

### ISSUE THREAD

**Issue by ionutm80** [rstrouse/ESPSomfy-RTS#120]
Hi, as the title says I'm having a problem meaning that in spite of the fact the the radio of the E07-M1101D transceiver seems activated I do not pick any signals from the motor shades. The are 4 shades with Somfy Altus motors controlled through a Situo 5 RTS remote. I'm using an ESP32-WROOM-32U module with external WiFi. I have attached some screenshots of the Radio pages and of the remote. No shade is paired yet but from the Wiki I understand that the transceiver should be able to pick up the signal since it is in receive mode. Pls help me ti debug it. As a side comment I also have a Somfy Connectivity Kit which picked the shades motors immediately and I can controll them through Tahoma app.
![IMG_3862](https://github.com/rstrouse/ESPSomfy-RTS/assets/68031938/a33d01a5-3596-4cbb-82ba-ae373c41c324)
![IMG_3861](https://github.com/rstrouse/ESPSomfy-RTS/assets/68031938/7c978623-259e-41ce-88d8-3c627ae580c7)
![IMG_3859](https://github.com/rstrouse/ESPSomfy-RTS/assets/68031938/1d709dbb-05ed-4add-bf32-3227ab259820)

**Comment by ionutm80** [comment]
Solve it, the remote is sending 433.38 instead of 433.42.

**Comment by ionutm80** [comment]
Solve it, the remote is sending 433.38 instead of 433.42.

**Comment by leonardpitzu** [comment]
Hi. I have the same remotes and I pick the signal from one of them intermittently. I already changes the battery and it's the same. It's got nothing to do with distance as I see the same even if the remote is 10cm away from the receiver's antenna. Any hints on troubleshooting this?

**Comment by rstrouse** [comment]
Run the Scan Frequency function while holding down one of the buttons.
