### ISSUE TITLE
Does it suppose to support also ESP8266?

### ISSUE THREAD

**Issue by zlymeda** [rstrouse/ESPSomfy-RTS#123]
Hi,

in the Somfy.cpp I see ESP8266 mentioned.
```cpp
#if defined(ESP8266)
    #define RECEIVE_ATTR ICACHE_RAM_ATTR
#elif defined(ESP32)
    #define RECEIVE_ATTR IRAM_ATTR
#else
    #define RECEIVE_ATTR
#endif
```

I was wondering if this could also run on ESP8266 (without the ethernet support)?

thank you

**Comment by rstrouse** [comment]
Unfortunately I never got around to rebuilding with the 8266 binaries.

**Comment by rstrouse** [comment]
I am going to close this because some initial checking with ESP8266 proved to be too limiting.
