### ISSUE TITLE
docu: ESP32 POE mounting holes

### ISSUE THREAD

**Issue by philipparndt** [rstrouse/ESPSomfy-RTS#129]
Hi, 

thanks for this project. Some note about the [docu](https://github.com/rstrouse/ESPSomfy-RTS/wiki/Simple-ESPSomfy-RTS-device#olimex-esp32-poeevb):

the new Olimex ESP32 POE revision "L" comes with mounting holes.
see: 
https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware
https://github.com/OLIMEX/ESP32-POE/tree/master/HARDWARE/ESP32-PoE-hardware-revision-L

<img width="289" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/2879650/40faf03f-a543-49bc-9033-811b6c7a6f65">

**Comment by rstrouse** [comment]
Did the documented pins for the original Olimex work for this board?

**Comment by rstrouse** [comment]
I updated the documentation to reflect revision L of this board.

**Comment by rstrouse** [comment]
Closing this for now.  Let me know if there are any other differences that I am not aware of.  I do not have this hardware.

**Comment by philipparndt** [comment]
@rstrouse I've received the new board and (Hardware Revision L) and can confirm that everything is sill working (I've tested the radio and ethernet as documented)
