### ISSUE TITLE
Link for buying hardware

### ISSUE THREAD

**Issue by jboesh** [rstrouse/ESPSomfy-RTS#135]
I am interested in getting started with your project and struggling to find the right hardware.  You made suggestions what I should buy but you still have many different options on for example ali express and amazon.  

To avoid buying (and having to return) the wrong hardware. I hardly dare to ask: do you perhaps have a direct link where I can buy it? (Wireless board) Of course it can be an affiliate link where you might earn something :-)

What I've found myself, can you confirm I can continue with these products?
[ESP-32S ESP-WROOM-32 ESP32](https://nl.aliexpress.com/item/1005002611857804.html?spm=a2g0o.productlist.main.1.5520e13aByfPgp&algo_pvid=bb9ac5ba-dd24-4453-b541-a3a46f4c226d&algo_exp_id=bb9ac5ba-dd24-4453-b541-a3a46f4c226d-0&pdp_npi=4%40dis%21EUR%216.29%214.91%21%21%216.63%21%21%40211b88f016929679876255046e1df6%2112000033324572898%21sea%21NL%21756153691%21&curPageLogUid=404iT5b9NvSm)
[connectors](https://nl.aliexpress.com/item/33010611220.html?spm=a2g0o.productlist.main.5.2fe54a51dHZj9T&algo_pvid=1ce71bbf-b164-446b-8231-4cd32fc689e3&algo_exp_id=1ce71bbf-b164-446b-8231-4cd32fc689e3-2&pdp_npi=4%40dis%21EUR%213.40%213.03%21%21%213.58%21%21%402132a1f916929685551044769eb981%2110000001130721031%21sea%21NL%21756153691%21&curPageLogUid=FEcdPAUKSXB4)
[and the transceiver](https://nl.aliexpress.com/item/1005002074380868.html?spm=a2g0o.productlist.main.1.db3d4140ez6W7O&algo_pvid=149716dd-3f86-4a1a-9f70-53fc004dc7ae&algo_exp_id=149716dd-3f86-4a1a-9f70-53fc004dc7ae-0&pdp_npi=4%40dis%21EUR%213.03%212.57%21%21%213.19%21%21%402132a1f916929684715543793eb981%2112000025798608305%21sea%21NL%21756153691%21&curPageLogUid=387vHW5sGKA1)

and I assume I also need a USB cable to plug the ESP board to an NAS or raspberry right?

**Comment by rstrouse** [comment]
The ESP32 module and transceiver you linked to will work great.  The connectors you linked to however are male to female you need female to female.  Each end of the wire will be pushed onto a pin on either the transceiver or the ESP32.

Yes you will need a micro usb data cable for initial firmware load and that can be used to power the ESP32 board from any USB port after the initial firmware is loaded.  Updates to the ESP32 are all done using wifi after the initial firmware is loaded.

**Comment by jboesh** [comment]
Thanks for the fast reply and confirmation! I still have doubts about buying from ali express because you have to wait a long time for delivery, but on the other hand you won't get it cheaper anywhere

**Comment by rstrouse** [comment]
If you want amazon here are some links but I am in the US.
https://www.amazon.com/Teyleten-Robot-ESP-WROOM-32-Development-Microcontroller/dp/B08246MCL5/ref=sr_1_1_sspa?crid=15T4CSRHQEK88&keywords=esp32&qid=1692999566&sprefix=esp32%2Caps%2C210&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1

https://www.amazon.com/CC1101-Wireless-Transceiver-915MHZ-Antenna/dp/B01DS1WUEQ/ref=sr_1_2?crid=2088B8H8ILKPL&keywords=cc1101&qid=1692999651&sprefix=cc1101%2Caps%2C191&sr=8-2
