### ISSUE TITLE
Percent of open

### ISSUE THREAD

**Issue by dgmltn** [rstrouse/ESPSomfy-RTS#136]
> No matter if I am standing on my head or in any other position, I cannot square a percentage of open in my mind. It doesn't work, 100% is not open and 0% is not closed.

I always think of it as, "if I'm standing in front of that window naked and my neighbor walks by, how embarrassed will I be?"

Seriously, thanks for your awesome work and writeup!

**Comment by rstrouse** [comment]
Thanks for the confidence!

I am never embarrassed, then again I might only be able to do the naked thing.  The ability to stand on my head long enough for someone to walk by was never really in the cards.  I guess if your feet smell and your nose runs you are upside down anyway.

**Comment by dgmltn** [comment]
This is an acceptable solution 👍
