### ISSUE TITLE
Changing motor display orders

### ISSUE THREAD

**Issue by bbs2web** [rstrouse/ESPSomfy-RTS#139]
This project is amazing! This was the first time tinkering with an ESP32 and your detailed guides made this an absolute breeze!

I first added the roller blinds in my office, then added the ones in the kitchen and then those in the TV lounge. The display order of the motors however unfortunately shows them in the order they were added, I had incorrectly presumed that this would be alphabetical, or that I could change the order manually.

Feature request:
Kindly asking for the ability to re-order the list of motors.

**Comment by rstrouse** [comment]
Not a bad suggestion.  I will add this to the enhancements list.

**Comment by rstrouse** [comment]
This will be in the next version 2.1.5 and I am doing testing on it right now.  You will be able to drag and drop the order in which you want them to appear.

**Comment by rstrouse** [comment]
Alright v2.1.5 has been released.  To change the order of the display simply drag and drop the desired position in the configuration section for the shades list and/or the groups list.
