### ISSUE TITLE
ESPSomfy not always responding

### ISSUE THREAD

**Issue by taugusti** [rstrouse/ESPSomfy-RTS#143]
I have a garage door on the ESPSomfy - and when it works, it works great!
The motor is a "Dexxo Optimo RTS" pn 5147629A V93-00.
I have one real issue - and maybe the other not-so-important issue is related - I include both below to give you the full picture.
I home you can help

**#1: no response after idle**
When the door / espsomfy have been idle for some time - I think like a day or something, it takes many commands to the ESPSomfy before the door starts moving.

I have tuned the radio and on a 1m distance I get about -30dBm.

The radio log shows 80-V when I click a remote. That should indicate 80-bit RTV protocol. If I use that, the garage door does not move. Both 56-bit and 80-bit RTS works.
<img width="334" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/15052792/73e9baf1-1ed8-4014-88f4-bd6611ae04f9">

**#2: not understanding remote commands**
I have added the remotes to the garage door, but the operation of them are not indicated in the ESPSomfy position. 
It seems in the log that the commands from the remotes are in an unknown format: "Unknown(15)".

**Comment by rstrouse** [comment]
You need to update to the latest version 2.1.4.  Support for the Dexxo was not added until this version.  It is 80-bit RTS.

**Comment by rstrouse** [comment]
When you set the Dexxo motor up choose Garage (3-button) this will allow you to control many more aspects of that motor.  Also, if you use home assistant don't forget to update the integration.

**Comment by taugusti** [comment]
Device went offline after online fw update
now reprogramming from scratch

**Comment by rstrouse** [comment]
Hmmm... That is the second report of this yet I have updated at least 10 at this point with no issues.

**Comment by taugusti** [comment]
I think it may have been my own fault
I think I might have mixed up the application / firmware / "onboard" versions
I have it running on 2.1.4 now - just need to get the radio and pairing to work again...
No more time today - will continue tomorrow.

**Comment by taugusti** [comment]
Ok, now up and running again on 2.1.4 (2.1.3 HASS integration)
codes from the remotes are now converted to "toggle".
I selected garagedoor and 3-button and everything seems to work.
I now look forward to try it after 24 hr unused :-)

Thank you for your support!

**Comment by rstrouse** [comment]
Great! Submit another issue if you have any more problems.

**Comment by taugusti** [comment]
Works like a charm now . thanks!

only issue seems to be that if I click toggle too fast - it ignores the message and I have to wait "some time" for the garage door to respond to toggle commands

**Comment by rstrouse** [comment]
This may be the motor not allowing commands right away.  How long is "some time" and I assume you are using the 3-button setting where it has an explicit up, down, and my command.

**Comment by taugusti** [comment]
Hi again
I have now tried to see if I can identify a pattern
but - it seems to work even with quite short intervals - down to about 1 sec.
From time to time it "blocks" for maybe 30 sec and then works again.
During this period the remote works - so it is apparently not the motor that fails
but I cannot find a pattern - and the problem is not present in normal use.
So - I think it is great!
