### ISSUE TITLE
Cannot seem to initialize radio

### ISSUE THREAD

**Issue by mvantschip** [rstrouse/ESPSomfy-RTS#152]
Hi all,

Big fan of this project and have been itching to try to automate my shutters with this software since I found the GitHub page.
This is my first time working in such a DIY fashion, so apologies for any miscommunication.

I cannot seem to get my radio signal to iniatilise in the "Radio" section. I have re-done my pins multiple times and tried to swap the TX/RX pins on multiple occassions, both inside the web app and on the pins. 

I am using the following hardware:
ICQUANZX CC1101 SMA antenna
ESP WROOM32 NodeMCU32-S with the following pin layout: https://i.imgur.com/zIwFHHL.jpg

Here is an album of images which attempt to show my pin allocation. I hope they offer a good view.
https://ibb.co/album/Wvxmcm

I think the issue may be the antenna, but first want to look for other options before purchasing another one...

Thanks in advance!

**Comment by rstrouse** [comment]
In looking at your images it looks like you have this hooked up like this (only 2 pins are correct)

Pin numbers represent the pin numbers on the transceiver.
1 - Black - GND (correct)
2 - Red - 3v3 (correct)
3 - Orange - GPIO23 - TX (incorrect)
4 - White - GPIO18 - CSN (incorrect)
5 - Yellow - GPIO19 - SCK (incorrect)
6 - Green - GPIO13 - MOSI (incorrect)
7 - Brown - GPIO12 - MISO (incorrect)
8 - Purple - GPIO5 - RX (incorrect)

It should be set up like this.
1 - Black - GND
2 - Red - 3v3
3 - Orange - GDO0 (TX) - GPIO13
4 - White - CSN - GPIO5
5 - Yellow - SCK - GPIO18
6 - Green - MOSI - GPIO23
7 - Brown - MISO - GPIO19
8 - Purple - GDO2 (RX) - GPIO12

I have color coded the pin locations if you leave the connections as you have them on the Transceiver
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/b5c343b9-40cc-4df6-b661-64a2c84d1924)

Then after you have rewired appropriately set your transceiver setup to be like this.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/2fe17961-cd95-4f36-aed5-172ce5dee46a)
