### ISSUE TITLE
SOMFY – Commande universelle 1841022

### ISSUE THREAD

**Issue by samourai64** [rstrouse/ESPSomfy-RTS#153]
hello
I have this command for  my gardens light who works fine with domoticz and a rfxlink box. The command is paired as blind but only "STOP" works.. When i clic on"STOP" the lights start for a few minutes. It's a "dry contact"

I try to update my system with your Simple ESPSomfy RTS device on an another mini PC.
The command paired with roller shade or shuter or garage3 buttons (not paired with 1 button)

But, and that's the probleme the "STOP" doesen't work alone. I must clic up or down before stop send the command and start my light

I hope you understad the problem in my poor english

Have you an idea to solve th problem?

Thank's for the help

**Comment by rstrouse** [comment]
Your English is a whole lot better than my French.  However, it would be great to get a log of the frames that are sent from from the remote.  I suspect that it is simply sending a my command to toggle it.  Start with the lights off.  Then clear the log and press the button to turn on the lights.  After a few seconds, click the button to turn the lights off.  This will tell me what protocol frames are being sent.  

The Garage (1-button) is a special frame that relates only to the KeyGo remote and have a sneaking suspicion that it is only sent to special motors.  For instance sending that frame to a Sonesse motor does absolutely nothing.

It is not outside the realm of possibility to add some of these toggle functions into the firmware and perhaps a device for it.

**Comment by samourai64** [comment]
Ok. This is the logs with my keygo command.
I press the button, the light tturn on
I press the same button after a few seconds. I thin'k that the lights turn off but i m not shure because they are on a electonic timer

the logs

[{"encKey": 164,
  "address": 16148017,
  "rcode": 1350,
  "command": "Toggle",
  "rssi": -76,
  "bits": 80,
  "proto": 0,
  "valid": true,
  "sync": 24,
  "pulses": [2499,2560,2515,2576,2502,2556,2521,2560,2513,2567,2517,2537,2522,2565,2518,2546,2526,2558,2500,2570,2516,2550,2520,2456,4822,1287,1296,1334,1266,680,640,1302,1311,668,654,663,645,1296,1309,1296,659,647,1320,658,648,24,1301,1289,1307,1306,1295,691,622,680,636,1301,681,657,669,626,689,648,668,636,1310,646,681,1286,1295,1291,1319,665,669,652,633,1305,1299,691,623,1312,675,646,1288,1321,631,661,672,650,1311,1317,1286,1290,1311,1296,1284,699,627,659,642,1321,1290,670,650,661,665,672,650,1291,668,654,659,669,1297,1282,644,679,666,645,674,661,653,648,682,633,670,647,663,681,641,660,664,648,670,660,663,644,682,657,1299,658,666,1293,658,658,1298],
  "time": "2023-09-15T23:32:39.742+0200"
},
{"encKey": 164,
  "address": 16148017,
  "rcode": 1350,
  "command": "Toggle",
  "rssi": -78,
  "bits": 80,
  "proto": 0,
  "valid": true,
  "sync": 12,
  "pulses": [634,1714,2552,2530,2515,2559,2517,2565,2499,2564,2511,2562,2517,2464,4820,1312,1270,1312,1294,664,649,1320,1285,666,679,640,644,1300,1316,1304,664,646,1285,689,655,1287,1298,1284,1299,1303,764,560,666,645,1297,684,643,676,636,678,645,681,656,1271,678,661,1293,1314,1295,1283,666,674,663,640,1293,1311,693,639,1286,669,658,1293,1295,690,643,670,638,1293,1322,1282,1297,1316,1294,1288,690,638,659,649,1298,1310,668,658,635,672,673,639,1314,646,682,1277,1299,654,668,654,665,672,646,664,663,668,654,662,650,645,679,660,645,674,634,679,645,680,634,668,647,1317,1297,661,654,1298,660,654,1297],
  "time": "2023-09-15T23:32:39.881+0200"
},
{"encKey": 164,
  "address": 16148017,
  "rcode": 1350,
  "command": "Toggle",
  "rssi": -77,
  "bits": 80,
  "proto": 0,
  "valid": true,
  "sync": 13,
  "pulses": [2508,2515,2538,2527,2568,2509,2573,2494,2560,2509,2573,2518,2450,4821,1311,1271,1312,1298,678,639,1306,1278,691,668,633,661,1298,1308,1306,651,616,1338,672,659,1290,1279,1311,1300,1292,693,634,663,643,1300,689,669,653,630,673,648,684,641,1295,665,649,1296,1314,1294,1309,644,681,639,672,1295,1294,692,639,1259,699,635,1317,1294,662,647,669,661,1306,1298,1306,1271,1316,1294,1310,695,609,659,648,1319,1303,669,633,665,674,1299,680,619,676,658,1293,654,661,1299,653,660,664,650,687,639,669,660,656,641,677,659,649,671,657,640,695,632,689,647,644,658,1316,645,661,1302,1302,655,644,675,659],
  "time": "2023-09-15T23:32:40.026+0200"
},
{"encKey": 164,
  "address": 16148017,
  "rcode": 1350,
  "command": "Toggle",
  "rssi": -77,
  "bits": 80,
  "proto": 0,
  "valid": true,
  "sync": 12,
  "pulses": [617,1767,2498,2558,2524,2551,2507,2573,2507,2574,2497,2569,2509,2456,4827,1302,1285,1323,1284,672,634,1316,1293,663,670,648,633,1320,1292,1312,642,658,1287,693,635,1292,1303,1312,1294,1289,647,672,658,653,1295,684,642,668,637,690,646,669,635,1304,675,654,1292,1303,1294,1307,649,671,659,657,1292,1310,642,656,1312,648,651,1319,1296,659,652,669,632,1313,1296,1312,1294,1294,1299,1306,651,669,658,631,1301,1310,672,651,658,677,1269,660,657,688,652,1316,643,653,1291,672,651,663,647,668,661,665,645,674,638,670,670,652,661,674,646,665,639,673,651,659,656,1301,658,656,1318,1295,644,677,636,677],
  "time": "2023-09-15T23:32:40.167+0200"
},
{"encKey": 164,
  "address": 16148017,
  "rcode": 1351,
  "command": "Toggle",
  "rssi": -76,
  "bits": 80,
  "proto": 0,
  "valid": true,
  "sync": 24,
  "pulses": [2527,2565,2507,2576,2514,2550,2523,2559,2510,2557,2538,2546,2518,2548,2503,2563,2514,2551,2529,2559,2524,2536,2537,2468,4807,1277,1314,1302,1292,679,634,1298,1309,674,672,634,654,1296,1314,1296,659,638,1317,658,664,673,637,665,643,1301,1305,1297,666,668,657,644,1298,1311,1300,703,601,673,651,1313,668,651,1288,1316,1286,1305,658,642,670,650,1319,1291,653,666,1302,677,629,1297,1307,672,649,658,665,1298,1314,1270,1315,1294,1289,1301,707,627,670,626,1314,1293,687,626,669,681,655,646,1299,655,670,656,661,1301,1305,628,667,684,657,645,676,657,649,669,634,665,675,643,685,632,665,654,662,661,669,635,683,669,655,1287,665,653,1309,647,655,1292],
  "time": "2023-09-15T23:32:53.522+0200"
},
{"encKey": 164,
  "address": 16148017,
  "rcode": 1351,
  "command": "Toggle",
  "rssi": -76,
  "bits": 80,
  "proto": 0,
  "valid": true,
  "sync": 12,
  "pulses": [640,1749,2518,2541,2552,23,2535,2509,2548,2517,2562,2530,2542,2517,2458,4816,1289,1321,1294,1315,635,653,1297,1340,648,653,667,649,1296,1289,1293,684,639,1373,607,644,674,637,659,669,1310,1290,1290,669,649,659,677,1296,1288,1293,691,644,668,660,1284,671,633,1312,1293,1316,1292,660,645,694,633,1314,1278,678,663,1278,703,625,1280,1314,682,656,645,652,1310,1317,1283,1289,1314,1294,1285,697,632,659,654,1293,25,1317,667,630,680,651,671,659,1318,646,658,1293,1293,665,671,646,658,657,672,645,658,674,644,662,657,668,645,661,664,668,660,644,670,647,662,655,668,1311,1275,674,665,1302,653,640,1302],
  "time": "2023-09-15T23:32:53.660+0200"
},
{"encKey": 164,
  "address": 16148017,
  "rcode": 1351,
  "command": "Toggle",
  "rssi": -76,
  "bits": 80,
  "proto": 0,
  "valid": true,
  "sync": 13,
  "pulses": [2504,2504,2577,2499,2534,2556,2545,2530,2549,2519,2561,2512,2466,4812,1279,1305,1301,1314,649,665,1295,1297,655,692,638,662,1292,1296,1306,669,640,1305,650,667,632,694,650,659,1303,1304,1277,701,634,664,649,1310,1299,1285,696,631,660,666,1291,680,633,1300,1306,1301,1285,691,618,702,635,1299,1303,641,668,1315,693,610,1283,1341,659,650,667,632,1292,1322,1292,1320,1284,1291,1287,722,606,662,641,1319,1313,664,628,660,665,1320,687,620,666,660,1283,669,662,1282,646,680,666,645,674,662,653,648,679,659,643,671,640,672,669,660,658,645,649,683,626,694,1285,674,646,1313,1268,684,634,670,649],
  "time": "2023-09-15T23:32:53.805+0200"
},
{"encKey": 164,
  "address": 16148017,
  "rcode": 1351,
  "command": "Toggle",
  "rssi": -75,
  "bits": 80,
  "proto": 0,
  "valid": true,
  "sync": 12,
  "pulses": [637,1746,2534,2553,2545,2529,2504,2563,2517,2560,2513,2551,2520,2454,4817,1292,1300,1305,1298,677,634,1298,1309,674,672,635,640,1312,1285,1299,681,647,1316,646,665,649,645,681,658,1297,1283,1289,682,638,691,637,1284,1320,1312,671,636,665,647,1294,665,645,1296,1309,1294,1311,666,635,685,643,1297,1284,672,658,1285,718,607,1288,1320,658,643,675,660,1292,1310,1295,1284,1297,1309,1301,651,661,700,624,1285,1297,680,636,688,653,1285,647,672,658,664,1299,656,666,1304,666,641,655,668,664,642,682,634,670,650,660,658,666,657,658,665,673,636,678,644,654,661,1303,655,668,1297,1287,662,669,661,656],
  "time": "2023-09-15T23:32:53.957+0200"
}]

**Comment by samourai64** [comment]
And the logs using the rfxcom command thrue domoticz and a blibd device on which i press just "STOP" 

[{"encKey": 166,
  "address": 131075,
  "rcode": 26886,
  "command": "My",
  "rssi": -74,
  "bits": 56,
  "proto": 0,
  "valid": true,
  "sync": 14,
  "pulses": [2510,2494,2488,2474,2512,2483,2498,2474,2496,2491,2501,2482,2506,2493,4815,1278,1296,1259,1294,625,660,1261,645,618,1283,1272,1270,1285,631,645,1271,660,634,1262,644,631,633,640,654,638,1270,1289,625,642,1273,1291,1273,1275,632,638,1296,1257,641,642,627,637,1284,643,622,1280,641,642,1274,1285,642,618,632,662,631,624,1294,1259,638,643,1276,1291,621,643,630,641,632,654,1271,1281,627,646,1272,1284,642,641,629,634,1285,1270],
  "time": "2023-09-15T23:40:48.861+0200"
},
{"encKey": 166,
  "address": 131075,
  "rcode": 26886,
  "command": "My",
  "rssi": -74,
  "bits": 56,
  "proto": 0,
  "valid": true,
  "sync": 14,
  "pulses": [648,32523,2482,2498,2486,2497,2486,2498,2484,2506,2477,2511,2472,2512,2495,2484,4843,1269,1285,1251,1298,635,634,1273,649,632,1263,1271,1279,1289,640,646,1259,654,621,1295,634,644,626,643,623,656,1263,1273,651,633,1286,1276,1253,1283,647,645,1260,1290,621,649,633,641,1278,646,628,1289,625,644,1276,1289,620,644,628,660,633,626,1271,1282,629,647,1273,1287,623,643,651,633,634,642,1274,1274,632,640,1276,1299,633,626,645,645,1259,1277],
  "time": "2023-09-15T23:40:49.004+0200"
},
{"encKey": 166,
  "address": 131075,
  "rcode": 26886,
  "command": "My",
  "rssi": -76,
  "bits": 56,
  "proto": 0,
  "valid": true,
  "sync": 14,
  "pulses": [647,32515,2511,2476,2504,2481,2495,2487,2520,2468,2502,2482,2483,2518,2485,2492,4817,1284,1268,1284,1279,617,653,1287,624,642,1276,1286,1270,1283,631,649,1269,633,635,1277,646,627,634,660,627,643,1276,1291,622,643,1279,1264,1270,1284,628,647,1273,1287,639,643,629,632,1285,644,622,1287,629,648,1273,1287,625,643,624,657,634,617,1302,1274,633,641,1275,1273,632,640,649,642,628,635,1284,1274,629,663,1259,1276,629,664,631,626,1272,1282],
  "time": "2023-09-15T23:40:49.149+0200"
},
{"encKey": 167,
  "address": 131075,
  "rcode": 26887,
  "command": "My",
  "rssi": -74,
  "bits": 56,
  "proto": 0,
  "valid": true,
  "sync": 14,
  "pulses": [2502,2506,2474,2487,2500,2487,2497,2504,2479,2502,2488,2495,2490,2474,4842,1289,1276,1276,1260,646,644,1275,630,641,643,626,634,645,1279,1269,633,643,1278,645,628,1263,1305,1271,632,638,1294,1260,653,620,1271,1287,639,642,630,633,659,625,1290,1262,651,641,619,656,1262,646,643,1277,632,627,1293,1259,639,646,624,658,636,640,1278,1271,634,640,1274,1273,631,642,645,642,630,634,1284,1289,634,634,1284,1268,637,636,629,645,1271,1283],
  "time": "2023-09-15T23:41:21.413+0200"
},
{"encKey": 167,
  "address": 131075,
  "rcode": 26887,
  "command": "My",
  "rssi": -74,
  "bits": 56,
  "proto": 0,
  "valid": true,
  "sync": 14,
  "pulses": [639,32534,2483,2508,2473,2494,2520,2462,2493,2506,2496,2477,2491,2501,2490,2498,4816,1290,1270,1290,1251,645,656,1265,648,619,653,632,632,641,1275,1271,638,646,1270,635,659,1275,1273,1261,640,643,1283,1282,620,647,1287,1276,622,654,634,634,638,642,1281,1259,641,648,637,637,1282,642,625,1267,653,644,1272,1261,645,642,629,636,658,628,1273,1281,630,648,1271,1288,623,640,651,633,635,643,1275,1276,633,643,1276,1273,634,642,648,618,1277,1284],
  "time": "2023-09-15T23:41:21.555+0200"
},
{"encKey": 167,
  "address": 131075,
  "rcode": 26887,
  "command": "My",
  "rssi": -75,
  "bits": 56,
  "proto": 0,
  "valid": true,
  "sync": 14,
  "pulses": [643,32517,2501,2489,2499,2489,2498,2486,2478,2503,2491,2503,2508,2454,2513,2491,4818,1286,1275,1273,1286,621,644,1282,630,639,646,627,635,640,1277,1297,633,644,1275,619,655,1266,1276,1273,631,653,1268,1281,629,646,1271,1285,639,643,629,637,632,641,1275,1275,638,647,646,625,1287,627,638,1275,632,26,640,1299,1277,633,640,622,642,632,639,1284,1272,655,640,1259,1271,656,641,632,625,647,645,1260,1291,620,649,1284,1277,620,656,638,638,1272,1260],
  "time": "2023-09-15T23:41:21.702+0200"
}]

**Comment by rstrouse** [comment]
Ok so if you want to use the single button the remote is actually sending an 80-bit command.  Set the bit length to 80 bits.  

However, does this have any dimming functionality or is it simply a toggle with 2 separate channels on the remote.  That being said I plan on adding a type that will simply be for dry contact.  It looks as if you should be able to click the my button (this is the same thing as stop in the RFX world) to toggle or use the toggle button on the 1-button garage door as 80 bits.

**Comment by samourai64** [comment]
hello
i try garage 1 button 80 bits ->no  sync
I try  roller shade 80 bits -> sync, but the MY button works only if i send UP or DOWN before: That's the same in 56 bits

So i observe yhat my KEYGO command send sometime in 80bits and some time in 56 its
For my RFXCOM its in 56 bits.....

thank's for your help

An another frenchie as the same problem. I ask him to post logs her.....

**Comment by rstrouse** [comment]
Ok so I am getting ready to release 2.1.6.  This will contain a setting for Dry Contact.  Part of the issue here is that ESPSomfy RTS is sending the correct commands but a garage door is not a dry contact.  The problem lies in the state calculation.  A garage door has a transit time that it must accommodate.  And if the button is pressed while that transit is occurring it should stop but if it is stopped it should reverse direction.

The dry contact type will eliminate the transit times.  There may be a delay for its support in the Home Assistant plugin but that will be over the next couple of days.

**Comment by rstrouse** [comment]
v2.1.6 has been released.  Simply change the type to Dry Contact and the bit length to 80 bits.  This should accommodate the dry contact features.  You do not need to re-pair the device if it is already paired.

**Comment by olivr2s** [comment]
Thanks for the responsiveness 😉

I just updated to version 2.1.6 and made the setting in dry contact with the message in 80 bits, but no reaction from the dry contact....😔

On the other hand, I use the Somfy box with 2 relays to control 2 non-RTS garage doors.  So for me, the 1-button garage management corresponds perfectly to the use of my garage with transit times and the stopping of the door during a movement and the reverse movement on an additional press.

**Comment by samourai64** [comment]
thank's for the work
i try the new release tomorow

**Comment by samourai64** [comment]
for me the application update break the esp...
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/97638377/80039465-b670-4a93-bf7d-2ec75a4832b7)

i try to reinstall 2.15 after a good night... and see

**Comment by rstrouse** [comment]
Clear your browser cache.

**Comment by samourai64** [comment]
the same reinstalling directly the new firmware and clear the cache....

**Comment by rstrouse** [comment]
Ok so cleared a couple of devices and found that the SomfyController.littlefs.bin file did not contain all the script changes.  Which meant that the SomfyController.onboard.esp32.bin file also did not contain all the script changes.  Please flash the SomfyController.onboard.esp32.bin file from the v2.1.6 repo.  Then restore the backup that was loaded into your downloads directory.

**Comment by samourai64** [comment]
the app and firmware 2.16 OK. perfect

I test tomorow the new dry contact and i feeback here
thank's

**Comment by samourai64** [comment]
Hello
Dry contact shared in 56 or 80 bits
But doesent command  the contact.....  but no reaction from the dry contact

If i can help for other test?....

Thank's

**Comment by rstrouse** [comment]
Yes without changing anything (the box paired to the ESPSomfy RTS device and the type set to dry Contact.  Click on the virtual remote tab.  Then press the my button.  Did it respond?

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/c3f416e9-c132-4a48-93e0-e341c0941cbd)

**Comment by rstrouse** [comment]
I think I know what is going on with this.  I did a timing by timing comparison for this command frame and noticed a minor difference.

Download and install the firmware from this link.  You only need to install this firmware and it will change the timings just a little bit.

https://github.com/rstrouse/ESPSomfy-RTS/blob/main/SomfyController.ino.esp32.bin

**Comment by samourai64** [comment]
sorry no change...
paired ok.
 but no reaction from the dry contact in 56 or 80 bits
i know that rfxcom is not the same but i found that on ha community
[https://community.home-assistant.io/t/rfxcom-how-to-send-specific-command/192534](url)

thank's for ypur help

**Comment by olivr2s** [comment]
sorry, no better on my side.
I updated with the latest file, tested in dry contact with 56 bits or 80 bits but no reaction from the relay.
Only the shutter mode with "up + my" or "down + my" works.

_I use this Somfy box for my garage doors, so it would be ideal if it works in 1-button garage mode because this corresponds perfectly to the operation._

**Comment by rstrouse** [comment]
Oh wow.  up/down + my is a bit of a surprise.  @samourai64 does your dry contact respond when you go to the virtual remote and use those commands?  I put that in there because I suspected something fishy about the command interface with that device.

**Comment by samourai64** [comment]
hello
Yes it's the same 
. I write  this in my fisrt message
"I must clic up or down before stop send the command and start my light"

**Comment by rstrouse** [comment]
@samourai64 that is not the same.  Go to the Virtual Remote tab and click on the My + Up and My + Down buttons.

**Comment by olivr2s** [comment]
I just tried all the keys on the virtual remote control in dry contact mode (56 bits and 80 bits) and none work, even up/down + my.

On the other hand, in shutter mode (56 bits and 80 bits), all the virtual remote control commands do not work, even my+up or my+down. Only up/down + my works.

With RFXCOM, this only works with the stop command.

**Comment by samourai64** [comment]
i confirm
Only "up" or "down" + "my" works

**Comment by rstrouse** [comment]
Wait the command from RXFCOM is the same as the My command (My = STOP).  In the somfy world there is no such thing as STOP.  It is stop when the motor is in transit and favorite postiion when it is not.  The remotes make no distinction with this as they only send the command.  The commands from either are identical.  I have verified this with the output from RFXCOM.  If you click the my button it will be an identical command to what is sent from RFXCOM with the exception of the address and the rolling code.

However, if the address is the same between the RFXCOMM and the ESPSomfy RTS the command will be ignored because the rolling codes will be off.  Somfy motors will eventually blacklist the address and need to be reset if the addresses for the remotes are not unique.

So what you are saying is that you first press the up button then you press the my button and it works.  UP + MY is a single command on the protocol.  So is it up or down then my that works?

**Comment by samourai64** [comment]
for the test the shade is configured as blind in 80 bits
if i clic on UP and MY (not in the same time but one after the other) thats work
If i clic DOWN and MY (not in the same time but one after the other) thats work

**Comment by rstrouse** [comment]
Thanks that clears things up.  Does this also work the same way when you have it set to 56 bits?

**Comment by olivr2s** [comment]
for me, up and my or down and my works both in 56 bits and 80 bits

**Comment by rstrouse** [comment]
Cool since the toggle command is only an 80 bit command I will send My instead of toggle when set to 56 bits.  The reason why up or down then my works is because of the favorite processing which does not come into play with a single button.  Pressing up or down forces the movement so the my command can be issued.

I will have a firmware shortly to try out.

**Comment by rstrouse** [comment]
Ok so download this firmware from here and set your bit length to 56-bits.  It should send the My command instead of toggle for any one button controller.

https://github.com/rstrouse/ESPSomfy-RTS/blob/main/SomfyController.ino.esp32.bin

**Comment by olivr2s** [comment]
Good morning,
I just did the firmware update remotely and a dry contact test at 56 bits and congratulations, it works :-)
I was able to see on my camera the opening of my gate after a first press, the stopping on the second press, then the closing on a third press.
Thank you for the responsiveness and smooth operation.
Maybe we will wait for confirmation of @samourai64

**Comment by olivr2s** [comment]
I also just tested it in garage mode - 1-button - 56-bit and **it also works perfectly**.
THANK YOU

**Comment by samourai64** [comment]
Hello
unfortunately for me it doesn't work, in 56 or 80 bits. On the 2 channels of the module
The pairing is done correctly but no order is sent. whatever key is pressed in virtual control
Sorry

**Comment by olivr2s** [comment]
> Hello unfortunately for me it doesn't work, in 56 or 80 bits. On the 2 channels of the module The pairing is done correctly but no order is sent. whatever key is pressed in virtual control Sorry

@samourai64 , de mon côté j'ai mis à jour le firmware avec le dernier fichier, vidé le cache, configuré en mode contact sec et 56 bits, enregistré et appuyé sur le bouton (pas de la télécommande virtuelle) et cela a fonctionné.
Après j'ai essayé en mode garage 1 bouton toujours en 56 bits , et cela fonctionne aussi avec le bouton de base.

**Comment by rstrouse** [comment]
> for the test the shade is configured as shutter in 80 bits
if i clic on UP and MY (not in the same time but one after the other) thats work
If i clic DOWN and MY (not in the same time but one after the other) thats work

@samourai64 I don't understand how the above would work and the firmware above doesn't.  Did you load the firmware above and configure as a 56-bit Dry Contact?

**Comment by samourai64** [comment]
hello
After hundred try... lol..... all works like a charm.... Ouf... The 2 chanels are configured .
Thank's for your help and the time

I have a request if is it possible
I use the dry contact with a light on a electronic timer. the dry contact send the order to the timer you start the light for some minutes and stop after

Is it possible to have the possiblity to auto off the light in the esp interface and the same in HA
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/97638377/13b8bae3-9d52-4166-9d6b-e0fd21922481)

thank's a lot

**Comment by rstrouse** [comment]
> I have a request if is it possible
I use the dry contact with a light on a electronic timer. the dry contact send the order to the timer you start the light for some minutes and stop after

The electronic timer is the issue.  If it were me I would be more inclined to use an automation in HASS that turns the light off after the time expires and get rid of that timer.  I don't think ESPSomfy RTS is the right place to start adding automations since Home Assistant has a rules engine in it.  Even then, knowing the state of the electronic timer would break it.

**Comment by rstrouse** [comment]
I am closing this as I think we have the heart of the issue resolved.  If there are any other issues please feel free to submit a new one.
