### ISSUE TITLE
WT32-Etho1 and D-Sun CC1101

### ISSUE THREAD

**Issue by daviss57** [rstrouse/ESPSomfy-RTS#154]
When connecting my WT32-Etho1 to the transevier D-Sun CC1101. Do the terminals labeled on the WT32 correspond with the Somfy GPIO numbers? i.e. IS I012 on the board GPIO-12 on the Somfy RTS dashboard?

Does the transcevier also need a seperate 3.3v supply?

Any pictrures, advice would be greatly appreciated.

I have followed the steps but I do not recieve any signals when I push the buttons on my remote.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/65281157/c25e5a42-614f-4b72-9e9f-9a498fcdda08)

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/65281157/138b3708-ad4b-447c-9ec1-67ff0e3b7f1c)

**Comment by rstrouse** [comment]
Yes but review the documentation for that board. You must change the settings to match the connection to the dsun.

**Comment by daviss57** [comment]
Thanks, I just wasn't 100% on the GPIO labels vs the labels on the board

**Comment by daviss57** [comment]
Ok, so i have tried a few times and I have not had any luck getting a signal when I press my remote buttons.

From the below table does it look like i have it wired correctly?

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/65281157/9cbf0056-6a8b-4500-9a9f-f0a5e2bd4ea8)

**Comment by Jumperm** [comment]
> Ok, so i have tried a few times and I have not had any luck getting a signal when I press my remote buttons.
> 
> From the below table does it look like i have it wired correctly?
> 
> ![image](https://user-images.githubusercontent.com/65281157/268720988-9cbf0056-6a8b-4500-9a9f-f0a5e2bd4ea8.png)

Hi,
with the documentation it work out of the box. 
https://github.com/rstrouse/ESPSomfy-RTS/wiki/Simple-ESPSomfy-RTS-device#wt32-eth01-models

**Comment by daviss57** [comment]
Thanks.

I've followed to the letter, the only reason I could think for it not
working was the IO pins may not have matched the software GPIO.
Do you know if there is a way to check if the transmitter is
functioning properly?

**Comment by rstrouse** [comment]
On the DSUN transceiver side make sure the pins are as they appear.  I have seen a couple of different pinout descriptions.  On the back of the board it should be labeled.  VCC, GND, SCK, MOSI, MISO, GDO2. CSN, and GDO0.

**Comment by daviss57** [comment]
Yes, I have double checked the labels to ensure I've wired them correctly.

Not sure where to go from here.

**Comment by rstrouse** [comment]
I know this is not what you want to hear but it may simply be a bad board.

**Comment by wutz-ESP** [comment]
in your screenshot  WT32-ETH01
SCK - - - - GPIO-15 - - - **GPIO 14**
GDO0 - - - GPIO-19 - - - **GPIO 02**  _TX_
CSN - - - - GPIO-16 - - - **GPIO 12**
GDO2 - - - GPIO-13 - - - **GPIO 35**  _RX_
MISO - - - GPIO-18 - - - **GPIO 04**
MOSI - - - GPIO-14 - - - **GPIO 15**

**Comment by daviss57** [comment]
Is the below what I should have

![Screenshot_20230920_134943_Excel](https://github.com/rstrouse/ESPSomfy-RTS/assets/65281157/06bdac16-3bd4-49df-8f5e-d81bb98793b7)

**Comment by wutz-ESP** [comment]
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/110094334/dca8cd98-8aaa-489b-bd89-5a916defedd0)

**Comment by daviss57** [comment]
Thanks,

That was before I changed them to match my table. I wasn't sure if the IO2
on the board was the same as GPIO-02 in the software

**Comment by daviss57** [comment]
> in this screenshot SCLK is GPIO-15
> 
> ![image](https://user-images.githubusercontent.com/110094334/269300382-dca8cd98-8aaa-489b-bd89-5a916defedd0.png)
> 
> there you can choose the board ![image](https://user-images.githubusercontent.com/110094334/269300962-bb4c1056-d819-46b8-b58a-511ef87dacf3.png)

Thanks

I missed that.  Hopefully that sorts it

**Comment by wutz-ESP** [comment]
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/110094334/17311883-5f22-4c83-8618-558660eae86f)

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/110094334/db342a41-a1c9-45b7-9f6f-b1270ec696de)

**Comment by rstrouse** [comment]
@daviss57 did you get this all sorted out?

**Comment by daviss57** [comment]
Unfortunately I think I fried the bord when I swapped over to the ethernet
cable. Tried resetting by reinstalling the software but its not emitting a
WIFI signal to log onto it

**Comment by rstrouse** [comment]
You have to jumper the firmware write pins on that board to flash the onboard firmware.  Then you must remove the jumper to get it to boot.  Then you have to be very careful to make sure you have wired everything properly or it can break the Ethernet chip.

**Comment by daviss57** [comment]
Yep, whatever I did, the little yellow LED no longer lights up/blinks. The
firmware goes through the full write process without issue but nothing
seems to happen when I reboot it.

Have ordered another one. Hopefully I can get that one going.

**Comment by wutz-ESP** [comment]
have you seen this instruction?
https://wolf-u.li/flashen-des-wt32-eth01-ein-esp32-mit-lan-wifiwlan/

On first boot you have to wait a long time before wifi getting visible.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/110094334/5d3d1c8d-11a2-4203-913d-e2914b00fd93)

**Comment by daviss57** [comment]
Thanks for your help. Recieved by new ESP32 today and have setup. All working 100%. Excelent software. Thank you.

**Comment by daviss57** [comment]
Closing now.
