### ISSUE TITLE
Same Software for radio sockets

### ISSUE THREAD

**Issue by do1kbl** [rstrouse/ESPSomfy-RTS#158]
Hello, its no Issues for ESPSomy-RTS but I find no Email address.

Its Possible that you create the same software for Radio Sockets? thats will be very nice

I have some with Dipswitches and used the library RCSwitch for that.

**Comment by rstrouse** [comment]
I did a deep dive into this and the ability to deal with the protocol detection is not possible and would interfere with the protocol detection for the RTx protocols.  In a send only scenario this would be fine but the pulse detection is incompatible with the current protocols.  Sorry, that I can't make this happen.
