### ISSUE TITLE
two devices different display

### ISSUE THREAD

**Issue by wutz-ESP** [rstrouse/ESPSomfy-RTS#160]
Update from 2.1.5 to 2.1.8
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/110094334/c7810789-7b79-4f83-bf1e-6a2330602d03)
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/110094334/1ec1ac17-f665-40b8-aa63-ab77170efee6)

One device switched to this display Firefoy and Google Chrome
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/110094334/14a27d53-e26b-49ff-96b6-6ebe26c87fbc)
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/110094334/63d8a82a-833b-4b35-baaf-0c23c6a671be)

Microsoft Edge
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/110094334/f33ea026-8df1-4805-a833-877733a71559)
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/110094334/21c63cc8-b24d-44d1-b36a-695d9638e9a8)

**Comment by rstrouse** [comment]
The browser cache needs to be cleared.  It is not picking up the right stylesheet.

**Comment by wutz-ESP** [comment]
Sorry, realised after opening this issue. That was the reason closing it immediately.
Dont know how to delete a wrong issue
