### ISSUE TITLE
Awning: Wind Sensor Command Does Not Work - Virtual Remote

### ISSUE THREAD

**Issue by BillyFKidney** [rstrouse/ESPSomfy-RTS#162]
Attempts to send the `wind` command result in no action from the awning.
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/0e308ba5-7b48-46ef-9b56-709066721f5c)

There is a wind sensor on our awning but I would like to be able to use the virtual remote to send the command as well.
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/dfbf1c4b-3a57-4d53-959f-71536521a04f)

Did I miss a configuration setting / setup step?

Do I need to link the wind sensor _remote_ like I did the Somfy remote?
<img width="434" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/c7692e22-6cc9-4773-9d1a-52358ccad1c4">

**Comment by rstrouse** [comment]
If you have a wind sensor then yes you should link it like a remote.  If you do not then sending a Windy command should have put a warning symbol over the icon and disabled the remote.

**Comment by BillyFKidney** [comment]
That answers what is wrong with the icon:
<img width="494" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/514fe492-b8ee-43e3-9319-50c738bd2906">

I am going to try and get the Wind Sensor added now…just have to figure out how to trick it to think it is attached to the awning….while shaking it in my hand. 

The instructions were not clear on the linking the Wind Sensor as a second remote (but logically it makes sense now). Perhaps as an enhancement the Wind Sensor check box is disabled until a second remote is connected and designated as the Wind Sensor?

**Comment by rstrouse** [comment]
Actually, if you do not have a sensor then you can emulate it with a weather app.

**Comment by rstrouse** [comment]
If it is already up then it cannot retract anymore.

**Comment by BillyFKidney** [comment]
> If it is already up then it cannot retract anymore.

Awning was fully extended from ESPSomfy RTS.

**Comment by rstrouse** [comment]
In your screenshot it is retracted.

**Comment by BillyFKidney** [comment]
Awning this moment:
<img width="482" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/91e0b9fe-f169-427d-b0ec-dd9ab2fe0893">

Button being pressed:
<img width="556" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/7ce219aa-b29c-4034-9c36-551f74e4098d">

No action from the awning motor.

<img width="514" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/a9d0cf85-730d-45ea-81f9-93c75042999c">

**Comment by rstrouse** [comment]
Since you have a wind sensor why are you trying to emulate one?  Did you pair your physical sensor with the motor?

**Comment by rstrouse** [comment]
What ESPSomfy RTS is doing is sending the windy frame to the motor.  It is simply acting like the Eolis.

**Comment by BillyFKidney** [comment]
I have the physical wind sensor working with the motor and ESPSomfy monitoring it.
This is the current status in ESPSomfy:
<img width="509" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/404bd26c-191c-41e5-8d93-5ff460cb115b">
<img width="428" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/6a949dca-c14c-4b3d-a34f-8bf70610a02a">

I will abandon using the virtual wind sensor.


However, the status in Home Assistant appears backwards.
<img width="556" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/5595f40e-3faa-4236-a3e3-1f9604c5dc55">
<img width="618" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/b8810907-0a03-4bd5-9502-8f73566a560e">
<img width="425" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/0d911a6a-926d-43fe-b43b-575d6b6d1346">


Is this due to the hardware wind sensor…or a different issue? (Thanks for so much help by the way)

**Comment by rstrouse** [comment]
It is due to the way the cover domain works in HA.  It is as correct as it can be because if you switch it the icons will be wrong and it will disable the wrong one.  If you flip the position in ESPSomfy RTS the icons will be wrong and the text will reflect the other way.  It is maddeningly stupid and despite complaints about it the devs insist it is correct.

**Comment by BillyFKidney** [comment]
Hmm, I will have to look at creating a template sensor to show the position in a different way.

Or perhaps HA should evolve the cover entity to better support awnings (Open = Extended, Closed = Retracted).

**Comment by rstrouse** [comment]
Yeah I don’t understand the resistance.  Bear in mind the limits are not in core the issue is with the ui project.
