### ISSUE TITLE
Reordering does not work on touch devices

### ISSUE THREAD

**Issue by devinfluencer** [rstrouse/ESPSomfy-RTS#164]
Hi,
on my Android 11 phone with Edge browser I can't reorder shades with drag and drop. Instead the list scrolls when I try to drag an item.
The same on a Windows 11 touch laptop.
Using the mouse works fine.
Solution might be to use two-finger drag for scrolling or to display a "move mode" checkbox on touch devices.
Thanks,
Thomas

**Comment by rstrouse** [comment]
Tap and hold.  The element will begin to float then you can move it.

**Comment by devinfluencer** [comment]
Android: No, the item is grayed out and when I move down the 'reloading' turning arrow appears. The grayed out state can only be reset by leaving the settings page.
Windows (Edge): Tap and hold has no other effect than scrolling.

**Comment by rstrouse** [comment]
In the next release this should be fixed.  It turns out that the touch screens have disabled the HTML5 drag and drop so I needed to perform some manual work.  The browser will do some detection then if the touch is held for 1 second it will change to a dragger.

**Comment by devinfluencer** [comment]
Super. I'm interested in the details as I have another web app using dnd in development. Can you give a hint where in the sources we are?

**Comment by rstrouse** [comment]
If you look at the code in index.js you will find that the answer is to revert back to pre-HTML5 processing and handle it all manually based on touch events.  You will find it around line #2246 on the setListDraggable method.  The key is that the press-n-hold needs to pause/wait for a period of time to switch modes or the scroll functions will overtake it.

**Comment by rstrouse** [comment]
v2.1.9 has been published that fixes this issue.
