### ISSUE TITLE
View use of remotes in HA

### ISSUE THREAD

**Issue by jboesh** [rstrouse/ESPSomfy-RTS#170]
Is it possible that I can view the state or use of the remotes in HA?  then I can use that information in automations.

**Comment by rstrouse** [comment]
Yes attributes on the entity indicate which remote address was used and whether that was an internal command to ESPSomfy RTS or a standalone remote.

last_cmd: last command sent
cmd_source: remote or internal
cmd_address: address used for the command
cmd_fired: unix time when the command was fired in milliseconds


![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/2edc7e26-bfa8-4888-a62b-85b2635e7e11)

**Comment by jboesh** [comment]
it looks like I dont have such attributes, can I enable all of them somehow?
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/71582854/50066792-47dd-4176-9ebf-e3ebde100237)

May I ask what internal as cmd source means? Is this through the internal ip / web server?
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/71582854/14067d02-952c-4f81-91ef-8362161b9ffc)

**Comment by rstrouse** [comment]
Cmd source is where the command came from.  For instance, remote or internal where remote means the command (up, down, stop, ...etc) was picked up from the radio.  Internal means that ESPSomfy RTS sent it out on its radio.

Has a remote or ESPSomfy RTS been used to move that shade since the integration was started?

**Comment by jboesh** [comment]
Now that I use the shutter via the remote, I can see the attributes. Will they remain there until a restart of HA, for example?

**Comment by rstrouse** [comment]
The remote address will always be the address you assigned to the ESPSomfy RTS shade.

**Comment by rstrouse** [comment]
The reason why the attributes disappear is because this data is only kept when the command event is fired in HA and is dropped when the entity is re-initialized.  This is just how HA works and there is no way around this.

**Comment by jboesh** [comment]
Thanks!
