### ISSUE TITLE
Direct FOTA Update

### ISSUE THREAD

**Issue by 011V32** [rstrouse/ESPSomfy-RTS#171]
Hello,
would be great if if you could extend the update mechanism.
A button in the UI to check for updates (or even check automatically) would be great.
And a (second) button to update the firmware and application direct from the repo without downloading it to the PC.
Additionally to update the esp also with the HA update so that the two applications match each other...
Thx.

**Comment by 011V32** [comment]
I don't know how, but RaspberryMatic did also the FW Update of the CCU over HomeAssistant:
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/22346481/abad3f69-aa97-464d-aebc-ba5a63104c29)

**Comment by rstrouse** [comment]
It is not that it cannot be done but it will need to be crafted from whole cloth as the data returned from github is massive in terms of size.  There is one library that does it but the dependencies do not match and I run out of PSP.  This is not a raspberry pi with an operating system and warehouses of system resources.  It is an MCU with many fewer resources.

So it is a slow slog through the data which I have already done.  I will do my best to get this function added.  At the very least it will check for the latest release.

**Comment by rstrouse** [comment]
I will be releasing this functionality next weekend.

**Comment by rstrouse** [comment]
Version v2.2.0 now includes a github update function to download and install the firmware and application from the repository.

https://github.com/rstrouse/ESPSomfy-RTS/wiki/Updating-ESPSomfy-RTS#github-update-method
