### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by remb0** [rstrouse/ESPSomfy-RTS#173]
I have this very nice software on a esp32. but I was wondering of  the bluetooth proxy could be added to the firmware,
so it can act with all my other esphome devices as one big bluetooth network.
Would this ever possible?

**Comment by rstrouse** [comment]
I am already over 95% of the program storage space.  So I don't think this is possible to tack on the BT libraries at this time.

**Comment by rstrouse** [comment]
I tried to make space for the bluetooth libraries and blew out the PSP.  With all the other functions of ESPSomfy RTS, the bluetooth modules just don't fit.  Sorry.

**Comment by Particpant** [comment]
I was about to make this FR, thanks for having given it a shot, even if unsuccessful!
