### ISSUE TITLE
Question regarding linked remotes

### ISSUE THREAD

**Issue by Croydon** [rstrouse/ESPSomfy-RTS#174]
First of all, thank you for your work! I haven't had yet the chance to actually use it, but it looks pretty much like something I wanted for years 👏  

I'm wondering what it technically means when a remote is linked.

So the following scenario: Each blind has a physical remote. Now I want to make this smarter, I use an ESP, your software, etc. I added a blind and linked the physical remote.  

Is the physical remote still able to control the blind fully independently from the ESP? Basically, I would like to know if the status quo still works if the ESP is powered off (for whatever reason).

Is ESPSomfy-RTS basically listening to all nearby remote -> blind RTS signals or is there a physical remote -> ESP -> blind connection then?

**Comment by rstrouse** [comment]
> Is the physical remote still able to control the blind fully independently from the ESP? Basically, I would like to know if the status quo still works if the ESP is powered off (for whatever reason).

Yes.  ESPSomfy-RTS simply acts like another remote independent of your existing remotes.

> Is ESPSomfy-RTS basically listening to all nearby remote -> blind RTS signals or is there a physical remote -> ESP -> blind connection then?

Yes.  While ESPSomfy-RTS acts like a remote, it is also a good listener.  So if you press a button on a remote it will hear that command and act on it if the remote is linked to the defined Blind in ESPSomfy-RTS.  There are a lot of integrations out there that simply act like a dumb remote and even some that require you to retire your existing remotes.  ESPSomfy-RTS does not do this and you should not use the same addresses of any of your existing remotes.  Normal motors allow around a dozen independent remote channels.

**Comment by rstrouse** [comment]
Btw just to be certain you understand.  You must pair ESPSomfy RTS with your blind just like you would do with a regular remote.  In essence you will have two remotes that control the blind, but only one of them can receive signals from other remotes.

**Comment by Croydon** [comment]
Thank you!

**Comment by RainerMaier3** [comment]
Dear rstrouse, also thanks a lot for your great work.
I have also integrated your ESPSomfy-RTS  into my HomeAssistant. It works perfectly :-)
I have one short question. I have in addition to my Remotes (Centralis) also a central remote Somfy Chronis where all Centralis are connected. Is it somehow possible to connect this Chronis as remote (listener) also to the shades? If the Chonis moved down all shades, it is not seen by the ESPSomfy-RTS integration.
Thanks a lot.
