### ISSUE TITLE
new font/style and re-opening

### ISSUE THREAD

**Issue by mihaiaka** [rstrouse/ESPSomfy-RTS#175]
Hi,

There is something wrong with the latest version of the application/littlefs.bin (I'm currently on 2.1.9)
It doesn't look as nice as before, but that is not the main problem, The "radio" tab has overlapping text:
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/50486008/0d56000a-d93c-42c1-9a36-24b23000a5dd)

Also to note here, in Chrome, if I close the TAB with the ESPsomfy page, and re-opening it with CTRL+SHIFT+T it will go to the "enter pin" page with the PIN already filled In and in PLAIN TEXT. I know that this is mainly for internal network use and should not be a huge factor, but I thought I would share this with you if you want to "tighten security". Maybe show starts * * * * or clear somehow the numbers and requests them again, or auto-login and actually open the exact page that was prior to closing the tab/etc.

Good luck and thank you for this project (again).
Mihai

**Comment by rstrouse** [comment]
Please clear your browser cache.  The browser cache is likely corrupted.

I'll have a look at the pin.

**Comment by mihaiaka** [comment]
well... that was what I thought as well, so I immediately pulled my phone out and tried a fresh/different new browser session from there, and had the same graphical glitch. I will try to re-flesh/reboot/etc and see what is the out come.

**Comment by rstrouse** [comment]
I am going to close this as it looks like the css file was corrupted on the device.  This happened to me once and I suspect it was probably some undetected glitch in the writing of the firmware.  The littlefs file system doesn't have all the sector read functions like a normal os.
