### ISSUE TITLE
Documentation of My-Position is missing

### ISSUE THREAD

**Issue by 011V32** [rstrouse/ESPSomfy-RTS#18]
I can't find any information about the My-position anywhere in the "Configuring the Software" documentation.
Maybe something could be added here?

**Comment by rstrouse** [comment]
Here you go.

https://github.com/rstrouse/ESPSomfy-RTS#setting-a-favorite

**Comment by 011V32** [comment]
Thanks, unfortunately I overlooked that. I just searched the wiki.
Maybe you could adopt that in the wiki, or at least refer to it?

Furthermore, I find a long button press in a software not very intuitive.
(I know that this is based on the original control, but probably almost nobody knows that either...)

**Comment by rstrouse** [comment]
The long button press is all we have at this point.  After I get v1.5.0 released I will be doing some documentation updates and putting a TOC outline on the main wiki.
