### ISSUE TITLE
Feature request: MQTT Auto Discovery support

### ISSUE THREAD

**Issue by xvisor16** [rstrouse/ESPSomfy-RTS#180]
Hi,

It would be amazing if ESPSomfy-RTS supported MQTT Auto Discovery (by home assistent). This makes it possible to use ESPSomfy without plugin in Home Assistent but even more important it would support a lot of different home automation software that also support MQTT-AD like domoticz for instance. I know there is an other tool which can control Somfy through a raspberry pi and MQTT-AD but I use ESPSomfy and it's just the best tool with the nicest interface so I would be amazing if MQTT-AD would be supported. For info about it:
https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery

Best Regards.
Peter

**Comment by rstrouse** [comment]
MQTT Auto discovery support has been added with the release of v2.2.0.  I would suggest if you are using Home Assistant to use the integration though.  There are just things that the MQTT device handler does not do.

https://github.com/rstrouse/ESPSomfy-RTS/wiki/Integrations#mqtt-auto-discovery
