### ISSUE TITLE
Infinite loading after shade pairing.

### ISSUE THREAD

**Issue by Bazzofski** [rstrouse/ESPSomfy-RTS#185]
Hi! 
After updating to the latest release (V2.2.0), I've noticed that the interface would start loading indefinitely after hitting "shade paired" on the shade prog menu.
 
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/58656201/8712010f-df6f-4114-9cbe-92353569405e)

**Comment by rstrouse** [comment]
Thanks, I'll have a look.  I suspect that this is a script error and a page reload will make it go away.

**Comment by rstrouse** [comment]
If you use the Github update function and install `Main` this issue has been fixed.  It was not sending the linked remotes after pair.

**Comment by rstrouse** [comment]
I am closing this for now as v2.2.1 was just released that contains the fixes for this error.
