### ISSUE TITLE
Bit Length value shows not the correct value

### ISSUE THREAD

**Issue by 011V32** [rstrouse/ESPSomfy-RTS#19]
The "Bit Length" field does not show the stored value, but the value that was last selected when switching through different blinds. (Even if another value is saved.)
However, the storage of the values in the backup is correct.

**Comment by rstrouse** [comment]
The next release will fix this issue.  The script was not setting the value on each load.

**Comment by rstrouse** [comment]
Update to v1.4.7 this should be fixed.

**Comment by 011V32** [comment]
That fixed it. Thx.
