### ISSUE TITLE
Indoor micro lighting radio receiver

### ISSUE THREAD

**Issue by open1999** [rstrouse/ESPSomfy-RTS#196]
Hello,

I use

https://www.somfy.me/en-gc/products/2401161/indoor-micro-lighting-radio-receiver

It'ok if you put "shadder", but in this case we have 3 buttons.

Dry contact don't run with lighting radio receiver.

Thanks

**Comment by rstrouse** [comment]
How does this work.  If you press the up button does it increase the brightness and decrease when you press the down button or is there no brightness involved and up turns it on and down turns it off?

**Comment by open1999** [comment]
It's very basic.

"up turns it on and down turns it off"

**Comment by rstrouse** [comment]
Update your device with the firmware from the Main repository.  To do this go to the gears section and select the System > Firmware tab.  Then click on the Github Update button and select Main.  Press update and it will install the update.
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/85019d21-fb72-48dc-bf77-f7e0c665edc9)

There is now a new option for a dry contact 2-button device.
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/54f08d30-c109-42fe-ae0c-227317015e24)

**Comment by open1999** [comment]
Hello

with v2.2.3 on HA we have error.

`Home Assistant Core
2023-12-11 11:37:03.676 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.espsomfy_rts.switch
2023-12-11 11:37:03.695 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'espsomfy_rts.switch': Platform not found (Exception importing custom_components.espsomfy_rts.switch).`

I rollback to v2.2.2

**Comment by open1999** [comment]
ok

**Comment by rstrouse** [comment]
I am going to close this for now as I believe we got you all squared away.
