### ISSUE TITLE
wESP32-PoE Won't Pair

### ISSUE THREAD

**Issue by mtwo** [rstrouse/ESPSomfy-RTS#198]
Hi! Thanks for providing this project!

I've installed ESPSomfy-RTS on a wESP32-PoE, which I've connected to a E07-M1101D v2.0 board that appears to be identical to the one used in your guide. With this setup, I see logs for my Somfy remote sending commands to my outdoor roller shutter, including the prog command when I press the prog button on the remote. However when I attempt to pair to the shade by pressing PROG in the pairing wizard, the shutter doesn't respond.

I read through some closed issues here and it looks like this typically means that the RX and TX pins are reversed. I _think_ that mine are correct (see photos) and are consistent with the setup that I entered into the radio configuration (screenshotted). I also briefly physically swapped the TX and RX pins to see if that would help and it did not.

Any suggestions? I did see one comment claiming that the pairing process had to be done extremely closely to the shutter controller. I'm standing about one meter away, though there's an exterior wall in between.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/1144235/3d38c43b-86dd-41dd-a167-7305e0b05ac6)
![20231129_174726349_iOS](https://github.com/rstrouse/ESPSomfy-RTS/assets/1144235/f3c1f2cd-1f5a-4c28-80ae-dd3fae3888d3)
![20231129_174750958_iOS](https://github.com/rstrouse/ESPSomfy-RTS/assets/1144235/c3bd358f-f54a-4702-b441-5f2aac002fca)
![20231129_174814357_iOS](https://github.com/rstrouse/ESPSomfy-RTS/assets/1144235/0ba7f7be-4696-42e5-ad97-19901f936858)
![20231129_174823795_iOS](https://github.com/rstrouse/ESPSomfy-RTS/assets/1144235/3ccd1ecc-f8fc-4536-8e79-7224382118f6)

**Comment by rstrouse** [comment]
Just to be sure.  Does your remote have the letters io on it?

**Comment by mtwo** [comment]
@rstrouse no, at least I don't think so. It's labeled Somfy Inteo White Single Channel and it fits into a decora wall box / plate.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/1144235/8fb8be69-f685-4dc6-bbaa-f218389b302f)![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/1144235/6e03f1e5-66af-4dcd-ae60-7a85045f5427)

**Comment by rstrouse** [comment]
I don’t have that equipment.  Look at the docs and find a suitable pin for GDO0.  You can get away without hooking up GDO2 and set the RX and TX to the GDO0 pin.

**Comment by mtwo** [comment]
No luck: I set RX and TX to the same pins, and tried this on IO4 / pin 15 and IO2 / pin 18. ESPSomfy won't let me set TX to a pin higher than IO30, and I'm assuming that TX requires analog I/O.

With TX and RX set to the same pins, I can still see messages coming from the remote, but ESPSomfy still isn't able to make the motor jog a second time during pairing.

Could this be caused by some kind of weird configuration on the existing remote? For example, if it was already configured with rolling codes or something like that.

**Comment by rstrouse** [comment]
Which button do you press on the remote to jog it the second time?

**Comment by mtwo** [comment]
I didn't: it would only jog the one time after holding the programming button on the remote for a few seconds. The programming message is recorded in the ESPSomfy radio logs.

However when I'm in the ESPSomfy pairing UI and I hold the remote's programming button until the motor jogs, the instructions tell me to press "prog" in ESPSomfy afterwards and that the motor should jog again to confirm that it's paired. This doesn't happen.

If I tap the programming button on the remote after attempting this, the motor will immediately jog, however I think that this just means that it's ending the pairing process.

**Comment by rstrouse** [comment]
You know this can happen if the motor memory is full.  I would reset the motor and try again.  You have all the symptoms.

**Comment by mtwo** [comment]
I'll try that!

**Comment by joaohess** [comment]
> I'll try that!

I’m having the same problem. Have you found a solution?

**Comment by mtwo** [comment]
I’m away for a little while, and I didn’t want to reset the memory on my shutters before I left, just in case they wouldn’t close. I’m going to attempt this in January.
________________________________

**Comment by rstrouse** [comment]
@joaohess are you using a wESP32-PoE?

**Comment by joaohess** [comment]
> @joaohess are you using a wESP32-PoE?

Sorry, no, I'm on a ESP-32 WROOM. But I managed to make it work! I'm new to github, so I didn't know closed issues were hidden! I've found the solution on [issue 121](https://github.com/rstrouse/ESPSomfy-RTS/issues/121): I added the URL /shadeCommand?shadeId=1&command=prog&repeat=20 while pairing and it worked!

Thank you

**Comment by rstrouse** [comment]
@mtwo did you finally get paired?

**Comment by mtwo** [comment]
Still on my trip, I’ll be home in a few days and I’ll attempt this once I have a few days back!
________________________________

**Comment by rstrouse** [comment]
Let me know how it goes.

**Comment by rstrouse** [comment]
@mtwo I am going to close this if you are still having pairing issues please open another issue.

**Comment by mtwo** [comment]
Yep, understood. I've been stymied by travel and bad weather when I haven't been traveling (the shutters are only accessible from outside). Once I have time to investigate further, I'll follow up here if I was able to fix it and I'll open a new issue if I can't. Apologies for the delay!
