### ISSUE TITLE
Link to Homekit w/o going through HA

### ISSUE THREAD

**Issue by ionutm80** [rstrouse/ESPSomfy-RTS#200]
Hi, first of all, excellent work. One question: is it possible to make the shades visible and controllable in Homekit without going through HA integration and then from HA to Homekit? Is there another path between ESPSomfy-RTS and Homekit?
Thanks a lot in advance!

**Comment by rstrouse** [comment]
No there really isn’t. The amount of work involved to make HomeKit communication is more time than I have to invest.

**Comment by babajun12** [comment]
You can take a look into homebridge if you don´t use HA

**Comment by ionutm80** [comment]
> You can take a look into homebridge if you don´t use HA

Hi and thanks for the hint, do you know what plugin shall I use in Homebridge for ESPSomfy-RTS?

**Comment by Calimerorulez** [comment]
I'm trying to get Homebridge with the plugin MQTTThing to work.

**Comment by Calimerorulez** [comment]
You can indeed use the MQTTThing plugin in Homebridge to set values via MQTT, and display the Somfy device as a shutter in Homekit. Only problem I have, is that position 0 in Homekit is fully closed, and in ESPSomfy-RTS, it is fully opened.

**Comment by rstrouse** [comment]
Actually if you check the box on the shade configuration it should invert these values.  I just tried it and it is correct on the MQTT side but it looks like the web app has missed something on the display.  Honestly, I cannot believe how utterly goofball it is that about half of the programs out there have this upside down.  The person who dreamed that up has to be from the southern hemisphere where everything is upside down.  That is the only thing that makes any sense.

**Comment by Calimerorulez** [comment]
In the MQTTThing plugin you can add some sort of conversion when it sends or receives a command via MQTT, so I created something like

`value = 100 - payload`

Only problem with that plugin is that it doesn't query the current position of the shades at startup. The dev isn't very active sadly.

**Comment by rstrouse** [comment]
I published v2.2.2 which will fix your issue with mismatched % of open between MQTT and the UI.  At this point you can have it reflect the position either way.

**Comment by ionutm80** [comment]
> In the MQTTThing plugin you can add some sort of conversion when it sends or receives a command via MQTT, so I created something like
> 
> `value = 100 - payload`
> 
> Only problem with that plugin is that it doesn't query the current position of the shades at startup. The dev isn't very active sadly.

Hi, can you share your MQTTThing plugin settings? I'm new to this and I do not know how it works. Thanks a lot!

**Comment by Calimerorulez** [comment]
> > In the MQTTThing plugin you can add some sort of conversion when it sends or receives a command via MQTT, so I created something like
> > `value = 100 - payload`
> > Only problem with that plugin is that it doesn't query the current position of the shades at startup. The dev isn't very active sadly.
> 
> Hi, can you share your MQTTThing plugin settings? I'm new to this and I do not know how it works. Thanks a lot!

Hi,

Something like this:

```
{
    "type": "windowCovering",
    "name": "Erker voorkant",
    "url": "mqtt://xxx.xxx.xxx.xxx:1883",
    "username": "homebridge",
    "password": "homebridge",
    "topics": {
        "getCurrentPosition": {
            "topic": "rts-somfy-beneden/shades/2/position",
            "apply": "return ( 100 - message );"
        },
        "setTargetPosition": {
            "topic": "rts-somfy-beneden/shades/2/target/set",
            "apply": "return ( 100 - message );"
        },
        "getPositionState": {
            "topic": "rts-somfy-beneden/shades/2/position",
            "apply": "return ( 100 - message );"
        }
    },
    "accessory": "mqttthing"
}
```

But it really depends on your specific MQTT configuration.

**Comment by Calimerorulez** [comment]
> Actually if you check the box on the shade configuration it should invert these values. I just tried it and it is correct on the MQTT side but it looks like the web app has missed something on the display. Honestly, I cannot believe how utterly goofball it is that about half of the programs out there have this upside down. The person who dreamed that up has to be from the southern hemisphere where everything is upside down. That is the only thing that makes any sense.

Maybe I overlooked it or am I lost now (which I probably am), but running 2.2.2, fully opened is still position 0 in MQTT.

**Comment by rstrouse** [comment]
Yep you missed it.  See below.
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/ed230c58-e2da-4e01-9a83-3f68042d32ff)

This is done by checking this box.
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/2b93dfe4-42a0-44af-8a8a-62115b775a4b)

**Comment by Calimerorulez** [comment]
Yes I missed it 😄. I was looking for it in the MQTT settings 😅
