### ISSUE TITLE
yellow and red explanation mark for roller shutter image

### ISSUE THREAD

**Issue by stas1000** [rstrouse/ESPSomfy-RTS#201]
Hi,

Sorry if this is stated in the docs smewhere but i am unable to locate.
Was just wondering if you could shed some light on what the attached screenshot indicates. The shad has change from a normal status to having a yellow and red explanation mark? The last thing i updated before this happened was setting the  MY position on the shade

<img width="87" alt="ESPSOMFY" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/22050639/12ce1ec5-6596-4610-9b3c-e01ba01c1480">

Thank You

**Comment by rstrouse** [comment]
That is a sensor reading for a windy condition.  You can only do this without a wind sensor from the virtual remote.

**Comment by stas1000** [comment]
Is there a way for me to stop it? I checked the virtual remote and both sunny and windy are unchecked

**Comment by stas1000** [comment]
Thank you I followed the instructions you gave in the HA forum. Pressed send in the virtual remote with the sensors unchecked.
