### ISSUE TITLE
ESPSomfy-RTS Chronis integration possible?

### ISSUE THREAD

**Issue by RainerMaier3** [rstrouse/ESPSomfy-RTS#202]
Dear rstrouse, also thanks a lot for your great work.
I have also integrated your ESPSomfy-RTS into my HomeAssistant. It works perfectly :-)
I have one short question. I have in addition to my Remotes (Centralis) also a central remote Somfy Chronis where all Centralis are connected. This was my central control before the Homeassistant integration. Is it somehow possible to connect this Chronis as remote (listener) also to the shades? If the Chronis moved down all shades, it is currently not seen by the ESPSomfy-RTS integration. It would be perfect, if the Chronis actions are also visible in ESPSomfy-RTS as it is for the single remote controls like the Centralis.
Thanks a lot.

**Comment by MrFl0w** [comment]
I have also a Telis 1 RTS, for the same purpose. Implementing something that listen to those types of remotes would be fantastic.

**Comment by rstrouse** [comment]
You should be able to link the remote today unless I am missing something.   The Telis 1 for sure simply sends the commands to the motor.  ESPSomfy RTS will capture these and reflect the state accordingly.

I would not expect that the schedules on the Chronis ever make it out of the remote.

https://github.com/rstrouse/ESPSomfy-RTS/wiki/Configuring-the-Software#linking-remotes-and-sensors

**Comment by MrFl0w** [comment]
Oups I missed that step! Now I have all m'y remotes linked! Thanks

**Comment by RainerMaier3** [comment]
Hi,
I have successfully shared the shade and one remote control (Centralis) (see picture)
Now as described in your link, I pressed the button "link Remote" to pair another remote (my Chronis)
unfortunately, nothing happened. The Info Window didn't closed and nothing happened, when I pressed the button "up" of my Chronis, except all shades are moving up.
Did I missed something?
![Paired shade](https://github.com/rstrouse/ESPSomfy-RTS/assets/76961376/3e276b98-9e23-45a8-9ec8-1ddb52231b68)

**Comment by RainerMaier3** [comment]
Here is a Photo of my config (other remotes for other shades are in the different rooms) Central unit is located in the Living room.
![IMG_2143](https://github.com/rstrouse/ESPSomfy-RTS/assets/76961376/6abd456f-575c-463c-b6d6-6f36059a4fce)

**Comment by RainerMaier3** [comment]
![IMG_2143](https://github.com/rstrouse/ESPSomfy-RTS/assets/76961376/aab4845c-4709-4d2e-8c4e-87fe192e0909)

**Comment by rstrouse** [comment]
When you press buttons on the Centralis remotes do you see any responses in the Radio log for them?

**Comment by RainerMaier3** [comment]
Ah, I cannot see a log, even if I am close, I think the signal is out of tune.
I also have seen, that some buttons, that I have pressed are misinterpreted (like an up press is shown as a my in the radio log). Is this also a sign of receiver is a bit out of tune?

**Comment by RainerMaier3** [comment]
Hi, that was it,! 
After tuning the radio, I was able to link the Chronis to every shade. Now it works ! 👍 
Thanks you so much 😃 🥳

**Comment by RainerMaier3** [comment]
Thanks for this great Work!
