### ISSUE TITLE
Unable to upload firmware to ESP32-S2

### ISSUE THREAD

**Issue by paede81** [rstrouse/ESPSomfy-RTS#207]
Hi

I can't upload the image file SomfyController.ino.esp32.bin to my ESP32-S2 mini. Esptool reports: Unexpected chip id in image. Expected 2 but value was 0. Is this image for a different chip model?

Is there somewhere an image for the ESP32-S2?

Thanks and regards,
Patrick

**Comment by paede81** [comment]
Was able to build the necessary file by myself. (just forked the github and run the action to generate the files)

Btw: in the build file, you have to change the version of esp32 from 2.0.9 to 2.0.10

**Comment by rstrouse** [comment]
I fixed the build file version and it generated the firmware.  Thanks for the version tip!
