### ISSUE TITLE
ESP32-S2: Service Error - Out of memory parsing JSON - when try to add new Somfy device

### ISSUE THREAD

**Issue by paede81** [rstrouse/ESPSomfy-RTS#209]
Hi
I'm currently running ESPSomfy-RTS on a Wemos S2 mini (ESP32-S2). When I try to add a new Somfy device with a name longer then 8 character, I'm getting the following message:

![Screenshot from 2023-12-22 10-40-33](https://github.com/rstrouse/ESPSomfy-RTS/assets/19265431/e28cd665-9a66-414b-969a-6033b8ef98e9)

Name: `StorenOb` --> working
Name: `StorenObe` --> error

And sometimes the device also crash afterwards and needs a reboot

**Comment by rstrouse** [comment]
I will have a fix shortly.  That's what I get for not allocating more memory than the shade definition needs.

**Comment by rstrouse** [comment]
This has been fixed in the Main repository.  I allocated more bytes for the json deserialization.

**Comment by paede81** [comment]
Thanks a lot. Issues fixed for me (thought it was due to the ESP32-S2 which has less memory than the ESP32)
