### ISSUE TITLE
Error updating from 2.2.4 to 2.3.0

### ISSUE THREAD

**Issue by VagnPetersen** [rstrouse/ESPSomfy-RTS#220]
Can not upgrade to newest version. I am getting the following error in HA:
"Failed to call service update/install. a byte-like object is required, not 'str'"

**Comment by rstrouse** [comment]
Update the HACs components to 2.3.0 first or perform the firmware update from the ESPSomfy RTS gui.

**Comment by VagnPetersen** [comment]
Thank you so much - it worked !
However, HACS did not announce that an update was available - a forced update did the trick.

**Comment by rstrouse** [comment]
It sometimes takes a couple of days for HA to catch up with the HACS updates.

**Comment by rstrouse** [comment]
I am going to close this one as the HA component should have published by now.
