### ISSUE TITLE
Login no longer available

### ISSUE THREAD

**Issue by Ric57100** [rstrouse/ESPSomfy-RTS#222]
I wanted to connect on the UI to install new firmware update but login page is not available.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/69900128/71e92167-0bde-402b-a14d-25bdc5e6a01f)

HA integration works well, but I can no longer manage anything from the GUI. Is it possible to launch an OTA update with a hidden url ?

**Comment by rstrouse** [comment]
Clear your browser cache or perform a refresh procedure if you are using chrome.

**Comment by Ric57100** [comment]
> Clear your browser cache or perform a refresh procedure if you are using chrome.

I've already done it. I have the same issue with Firefox, Chrome and Edge.

**Comment by rstrouse** [comment]
What firmware version are you currently on?

**Comment by rstrouse** [comment]
It looks like the filesystem has been corrupted.   This can happen when another process on the esp32 commits data to the filesystem when it is updating.   I am working on making it so the filesystem is not written to during this process but in the meantime it means that the firmware will need to be updated again.  Please make sure you have a current backup.  To do this you can run the following command.

`http://<ip addresss>/backup`

Then double check to ensure that file is not empty.

Next run the following command and let it complete without moving any of your motors until it has completed.  This may take a few minutes.

`http://<ip address>/downloadFirmware?ver=v2.3.0`

At the end of this it should have refreshed the file system files for you.

**Comment by rstrouse** [comment]
@Ric57100 did you get squared away?

**Comment by Ric57100** [comment]
Sorry for the late response. Yes, I managed to solve my issue by applying latest firmware from scratch and adding my motors one by one.
