### ISSUE TITLE
Groups not inverting

### ISSUE THREAD

**Issue by lukeskymuh** [rstrouse/ESPSomfy-RTS#224]
Hi,

What a amazing work! Thank you!
I just have a minor problem:

I made a group with a normal shade and a shade with inverted commands( up and down). Apparently the invertion of the commands iof the shade is ignored if controlled via the group.

BR Luke

**Comment by lukeskymuh** [comment]
Thank you!

**Comment by rstrouse** [comment]
v2.3.1 is in release.  It has the ability to invert the commands on groups.

**Comment by lukeskymuh** [comment]
Thank you for implementing. Unfortunatly my Problem is that only one shade of the group has to be inverted. Currently I can only invert all or none. It would be great if I could Invert a single shade of a group.
