### ISSUE TITLE
SIMU pairing impossible

### ISSUE THREAD

**Issue by schumissimo63** [rstrouse/ESPSomfy-RTS#231]
Good morning,
I have SIMU brand shutters, espsomfyrts is correctly configured, I was able to scan all my shutters and read the data specific to each one, but by pressing the "prog" mode on the remote control it is impossible for me to pair them , I have an error message like this "500 service error service: PUT /addshade Out of Memory parsing JSON". I should point out that I have the latest version of espsomfyrts and that I also read topic #212 which deals with this problem. Thanking you in advance for your help.

**Comment by Jezza34000** [comment]
Try UP+DOWN instead of PROG it should work to enter in programmation mode

**Comment by schumissimo63** [comment]
Thank you for your response, I pressed UP+DOWN, the shutter went down then went back up to mean that it was in PROG mode but it was impossible to pair. I am attaching some photos, am I correct in the settings, please?
![2024-01-10_153339](https://github.com/rstrouse/ESPSomfy-RTS/assets/76776295/4a0b824d-a9d2-4227-832a-5e59f437f45a)
![2024-01-10_153323](https://github.com/rstrouse/ESPSomfy-RTS/assets/76776295/f19a6881-50be-4482-8712-3de1d41e692d)
![2024-01-10_153302](https://github.com/rstrouse/ESPSomfy-RTS/assets/76776295/993b1801-bb68-42f3-a558-ade83c498e04)

**Comment by Jezza34000** [comment]
All the commands that we can see in your logs come from the original remote control of your shutters, do we agree?
Because if this is the case your configuration is not good, you cannot add a virtual "remote control" to ESPSomfy RTS which has the same address.

In "Remote Address" you can re use 196607 this addresse is alreday in use by your physical remote, put something else randomly and after use "Add Shade" and Pair it

**Comment by schumissimo63** [comment]
yes, that's right, the logs come from the wall switches which control the shutters. I just tried to pair by putting a random number (163400) but that doesn't work either. On the other hand, I managed to program the shutter using the "group" tab.
![2024-01-10_162400](https://github.com/rstrouse/ESPSomfy-RTS/assets/76776295/18735481-bce9-49be-ab96-f4d68d1d75a1)
![2024-01-10_162444](https://github.com/rstrouse/ESPSomfy-RTS/assets/76776295/7b962419-435a-4ec2-a383-85accf52676f)

**Comment by schumissimo63** [comment]
I installed version 2.2.1 and successfully did the pairing. Could this be a bug?

**Comment by rstrouse** [comment]
> I installed version 2.2.1 and successfully did the pairing. Could this be a bug?

2.3.1 is a pre-release and has many updates as I work through finishing off features.  This pre-release likely had partial functionality for Rooms in it so yes it is likely a bug but looking at the code, the room data has been worked out already.

**Comment by schumissimo63** [comment]
@rstrouse I wanted to thank you for this excellent work, thank you very much.
