### ISSUE TITLE
Sofmy

### ISSUE THREAD

**Issue by Nickduino** [rstrouse/ESPSomfy-RTS#234]
My OCD can't take it!

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/9784237/b802f49c-dbbc-4c47-996f-34bd5beaa00c)

**Comment by rstrouse** [comment]
Funny.  If my lysdexia had seen it I would have been bothered by it too.

**Comment by Nickduino** [comment]
That's the point of dyslxiea: to keep your OCD in check.
