### ISSUE TITLE
Pinout for Wemos S2 mini

### ISSUE THREAD

**Issue by nardev** [rstrouse/ESPSomfy-RTS#236]
I see you have a build for this one but i can't find proper wiring.

Any help?

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/696054/0dff3ef4-a155-48b1-88a6-1b70350c4062)

**Comment by rstrouse** [comment]
I have not build an S2 but based on the peripheral descriptions for the pins I would avoid the following pins 0, 3, 15, 16, 17, 18, 33, 34, 35, 36, 37, 38, 39, 40.  Pins 0 and 3 are bootstrapping so avoid the trouble.   Pins 33 - 38 are for the octal flash so just so the manufacturer didn't accost them for multiple versions I just avoid them.   Pins 39 and 40 are JTAG pins so avoid those.

So as a guess use the following but really any pin for any purpose except the above pins should be fine.  You could also used 33-38 if the board doesn't monkey with the SPI flash.

Pin | Description | ESP Pin
-- | -- | --
1 | GND | GND
2 | VCC | 3v3
3 | GDO0 - This is the TX Pin | GPIO 4
4 | CSN | GPIO 5
5 | SCK | GPIO 7
6 | MOSI | GPIO 9
7 | MISO | GPIO 11
8 | GDO2 - This is the RX pin | GPIO 6

**Comment by rstrouse** [comment]
Let me know when you have it working and I will include these recommendations for the S2.

**Comment by nardev** [comment]
This was the reason why i needed this.

![Screenshot from 2024-01-14 09-17-13](https://github.com/rstrouse/ESPSomfy-RTS/assets/696054/3c5be557-0d44-403a-8a38-c5d0af673668)

![Screenshot from 2024-01-14 09-17-07](https://github.com/rstrouse/ESPSomfy-RTS/assets/696054/d794583e-164b-423e-8026-acf0a7d3da44)

**Comment by rstrouse** [comment]
Awesome!

**Comment by nardev** [comment]
I figured, that would be the smallest form factor and also USB-C option. With shipping it's like 5$ for several PCBs. If you want, i can send you some.

**Comment by rstrouse** [comment]
I bought a Seeed Studio Xiao S3 and C3.  These are really small but I am most intrigued by the external antenna decal.

https://www.amazon.com/dp/B0B94JZ2YF?psc=1&ref=ppx_yo2ov_dt_b_product_details

**Comment by paede81** [comment]
I have an S2 and this is my GPIO configuration:

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/19265431/d1a8e62f-ef42-49d4-8385-62ad8915141e)

**Comment by rstrouse** [comment]
Thanks I was unsure of the DAC pin 18.

**Comment by nardev** [comment]
Already ordered PCB, would be able to set it the way in the table up and let it work?

**Comment by rstrouse** [comment]
It should work with either configuration.  In the end we can add the boards to the config to auto select the pinouts.  The system does this now based on the chip model.

**Comment by nardev** [comment]
Just tried uploading ESP32-S2 version to "Wemos S2-Mini", it writes the fw ok but AP never gets up.

Other than that, any other fw/code works ok on the board, can you please check pins?

It's same board like this one: https://xyzdims.com/3d-printers/misc-hardware-notes/iot-wemos-s2-mini-esp32-s2/

Anything sensitive in code that puts board in other modes?

**Comment by nardev** [comment]
@rstrouse sorry, on the other thread i was actually talking about this one.

**Comment by nardev** [comment]
@rstrouse 

This is what i get:

```
$ esptool.py --port /dev/ttyACM0 flash_id
esptool.py v4.7.0
Serial port /dev/ttyACM0
Connecting...
Detecting chip type... Unsupported detection protocol, switching and trying again...
Detecting chip type... ESP32-S2
Chip is ESP32-S2FNR2 (revision v0.0)
Features: WiFi, Embedded Flash 4MB, Embedded PSRAM 2MB, ADC and temperature sensor calibration in BLK2 of efuse V2
Crystal is 40MHz
MAC: 84:fc:e6:cf:4a:ba
Uploading stub...
Running stub...
Stub running...
Manufacturer: 20
Device: 4016
Detected flash size: 4MB
Flash type set in eFuse: quad (4 data lines)
```


The wifi AP doesn't get created at all.

**Comment by rstrouse** [comment]
Unplug the transceiver and see if it starts.  However, the unsupported detection protocol seems to point to the wrong board type for the onboard file.

**Comment by nardev** [comment]
Same thing just happened on the other board which was working (ESP32 chip) but as soon as i connected the module, it started ok.

**Comment by nardev** [comment]
I'll try the same with wthi ESP32 S2/2S

**Comment by rstrouse** [comment]
That is the one chip I do not have is an S2 but I do have a few S3s.  The S2 I ordered has been cancelled twice so I will try again.   What are you flashing with?  Did you pull the zip file from the release?

The other thing that is weird is that it is showing FNR2 which if I read the datasheet correctly is only 2mb of flash.   That wont work if it is correct because the firmware alone is 1.2mb and the filesystem is 1.4mb.  It is possible that the esptool version does not have the correct board definition.

**Comment by nardev** [comment]
Can you reach me, i'll send you a few. vedran@nardev.org

**Comment by rstrouse** [comment]
I already ordered 4 just now.

One other thing is that it looks like from the screenshot it is not returning all of the data.   Check to see if there is a Javascript error in the console.  It will be something like an cannot read maxXXX property of null.   If that is the case flash the pre-release of v2.4.0 using the onboard file.   This has some trimming on the json output.

**Comment by nardev** [comment]
It was my fault somewhere. I have everything up but i can't restore the backup...

It does restore ip settings but remote codes and timings, it just skips it :(

**Comment by nardev** [comment]
Ou, i got everything back after the reboot. COOL

**Comment by nardev** [comment]
Just to confirm that the wiring schema is correct.

**Comment by cook1emr** [comment]
> Pin | Description | ESP Pin
> -- | -- | --
> 1 | GND | GND
> 2 | VCC | 3v3
> 3 | GDO0 - This is the TX Pin | GPIO 4
> 4 | CSN | GPIO 5
> 5 | SCK | GPIO 7
> 6 | MOSI | GPIO 9
> 7 | MISO | GPIO 11
> 8 | GDO2 - This is the RX pin | GPIO 6

I have tried the above pin mapping, however am finding that blinds/garage doors are not very responsive compared to the esp32 wroom variants. Has anyone had success with other pin mapping?

@paede81 mapping would not pair for me.

This pinot seems to indicate mosi, miso, sck are on the 30 pins https://images.app.goo.gl/GXt7j6WAyMAc9o5GA however TX seems to not work when on those pins
