### ISSUE TITLE
MQTT Auto Discovery not available after restart of client

### ISSUE THREAD

**Issue by xvisor16** [rstrouse/ESPSomfy-RTS#241]
After an MQTT-AD client is restarted the ESPSomfy-RTS stays uncontrollable until a reboot of ESPSomfy.
This means that every time you need to completely restart ESPSomfy after an update of the MQTT client software.
Other solutions like Zigbee2mqtt or ZwaveJSUImqtt don't need that they are available after just a few seconds after restart.
Probably this has to do with those tools continuously sending data out to MQTT.
Is at possible to have ESPSomfy send a discovery/status packet or something every minute when the Publish Discovery box is ticked?

**Comment by rstrouse** [comment]
I'll look at what I can do.

**Comment by rstrouse** [comment]
In v2.3.1 the software will persist the disco topics and drop them when the reference is removed.  This should allow the subscriber to catch these whenever they subscribe.

**Comment by xvisor16** [comment]
Hi @rstrouse,
I've updated to 2.3.1-pre. But this didn't help. The same effect occurs.

**Comment by rstrouse** [comment]
Install Main.  I haven't had time to rebuild the pre-release yet with the new commit.

**Comment by xvisor16** [comment]
Installed Main and the problem is solved! Thanks 🎉
