### ISSUE TITLE
Room managment with home assistant

### ISSUE THREAD

**Issue by Pulpyyyy** [rstrouse/ESPSomfy-RTS#244]
Hello Rstrouse,

I'm still using this great combo with home assistant and I'm still very satisfied.
I discovered that you can only select one zone/room for all rts devices.
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/32004297/e80ee430-b7d2-4faf-911b-1c7f1db59d34)
I assume the room is inherited from the one assigned to the integration.
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/32004297/a94a1303-3610-4773-a986-cce5561faf63)
May it be changed, as obviously having all my covers in the same zone/room isn't the same as reality.

Regards,

**Comment by rstrouse** [comment]
Yes you can change this by clicking on the entity then turning off Use Device Area.  After that you select the room that it is in.  I am adding new functionality with 2.3.1 that allows you to define rooms in ESPSomfy RTS but I am not sure I will push theses down to HA at this point.

**Comment by rstrouse** [comment]
I assume you have gotten this squared away. v2.3.1 was released and it contains the ability to assign rooms in the UI.  I did not try to mirror this functionality into HA since I would never be able to keep them in sync.

**Comment by Pulpyyyy** [comment]
Thanks !
Just in case, room is size limited to 20 chars

**Comment by rstrouse** [comment]
Yes it is limited to 20.  I am pushing against a hard memory limit on the ESP.  But realistically, most folks seem to replicate the room name in the name of the shade.  You don't need to do this as the room will appear above the name.
