### ISSUE TITLE
Case for ESPsomfy on printables

### ISSUE THREAD

**Issue by bggsolar** [rstrouse/ESPSomfy-RTS#245]
Hi @rstrouse, thanks for the good work!
In the meanwhile I successfully managed to install and run ESPSomfy on an ESP32c3mini module combined with a CC1101 radio-module.
For both of them I created a combined case and just uploaded the stl-files for 3dprinting to printables: https://www.printables.com/de/model/726440-espsomfy-rts-case-for-esp32c3-mini-and-c1101

Feel free to share, use, remodel and have fun!

Cheers!

**Comment by rstrouse** [comment]
Awesome! I will add it to the docs.
