### ISSUE TITLE
Loosing Ability to use ESPSomfyRTS device through HA

### ISSUE THREAD

**Issue by Coolbreeze68** [rstrouse/ESPSomfy-RTS#246]
Hi,

Happy new year and thanks for this useful project !!

Actually Im facing an issue. At a certain amount of time Im loosing my Somfy buttons in HA, they are disabled.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/26818940/b5b20703-0ac3-4a44-a0c6-ec6caff5fd04)

The only way I found to enable them back is to untick and tick again "Publish discovery" and save.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/26818940/2d998425-5818-41fa-81dc-b3334af215ad)

Then my buttons are enabled again

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/26818940/010521c3-4cec-400c-9c1d-c1883904f9c5)

I wonder if we could have a new param in the firmware to set to force send a Discovery message every x min ( like an heartbeat )

Or I might miss something I can do on my side.

Thx a lot 

Christian

**Comment by rstrouse** [comment]
Update from Main using the Github update.  The MQTT configuration is persistent in the upcoming version.  Why MQTT-AD over the HACS component?

**Comment by Coolbreeze68** [comment]
Tbh I didnt see that component exists :/. 
Looks like I cannot use HACS with HA Os. I'll give a try installing it manually.
Thx a lot anyway

**Comment by rstrouse** [comment]
I use HACS with HAOS just fine.

**Comment by rstrouse** [comment]
If you do some searching there are a number of tutorials out there to get HACS on HAOS.  It is pretty easy but it is a few steps.

https://www.makeuseof.com/home-assistant-install-hacs-custom-addons/

**Comment by Coolbreeze68** [comment]
Yeah I've done my searching and I could install it. Indeed it is better that way thank you.

**Comment by rstrouse** [comment]
HACS is a good option and the plugin supports many more features.
