### ISSUE TITLE
Alert on shutter

### ISSUE THREAD

**Issue by open1999** [rstrouse/ESPSomfy-RTS#248]
### Describe you new feature you'd like

Hello,

I installed V2.3.1.

What is it this alert ?

![PrtScr capture](https://github.com/rstrouse/ESPSomfy-RTS/assets/25722103/ac4843ee-c8e6-4244-9e50-d9c877b36690)

**Comment by open1999** [comment]
resolved

**Comment by rstrouse** [comment]
Glad you got it resolved.
