### ISSUE TITLE
Wind sensor disappeared in Home Assistant after upgrade

### ISSUE THREAD

**Issue by pfak** [rstrouse/ESPSomfy-RTS#252]
### Hardware

ESP32

### Firmware version

v2.3.1

### Application version

v2.3.1

### What happened? What did you expect to happen?

I upgraded to v2.3.1 and there is no Wind sensor entity exposed to HomeAssistant. I still see my wind sensor remote is paired.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/195072/d4f255c7-a95d-486f-a5ae-8c3bf6eb55e7)

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/195072/182d9b90-55d8-42e1-a709-85867bc2fd5e)

### How to reproduce it (setp by step)

```bash
Upgraded from v1.7.2 to v2.3.1
```

**Comment by rstrouse** [comment]
That is weird because I do not see the backup and reboot options in your display either.  Are there any errors in your logs and did you install the official release or the pre-release?

**Comment by pfak** [comment]
The Home assistant component was on 2.3.0 when I updated the firmware and application to 2.3.1.

Order of events:

1.I was on HA 2023.5, updated to HA 2024.1
2. Noticed ESPsomfy HA component could not connect to ESPsomfy. 
3. Updated to 2.3.0 component 
4. Still could not connect/control via HA 

Few days go by... 

5. Updated ESPsomfy application and firmware from 1.7.3 to 2.3.1
6. Could connect/control via HA, no wind sensor entity 
7. Updated to 2.3.1 for the component, and I still do not see the sensor for wind.

There are no errors, and I installed only the official releases.

**Comment by rstrouse** [comment]
First, go to home assistant an click reload on the device.  It will be under the 3 dots next to the configure button.  

If that doesn't fix it please upload a backup from your ESPSomfy RTS device.

**Comment by rstrouse** [comment]
I will have a look.

**Comment by rstrouse** [comment]
Do you only have a wind sensor and no sun sensor.

**Comment by pfak** [comment]
I believe so. The installer was not too clear on it, but there's only one battery powered remote on the unit.

**Comment by rstrouse** [comment]
For now edit the shade and check the sun sensor checkbox.   Then go to HA and reload the integration.

**Comment by rstrouse** [comment]
@pfak update the plugin and the firmware to v2.3.3 and it will automatically add the wind sensor for awnings regardless of the sun sensor settings.
