### ISSUE TITLE
Telis 4 Remote - Shade Status with Group Remote

### ISSUE THREAD

**Issue by ecastete** [rstrouse/ESPSomfy-RTS#256]
I searched the issues and didn’t find any notes about this software configuration scenario.

I have a Telis 4 remote with the fifth position being group mode.  When I sent commands from th remote to the group of sheds the status change was not shown in the ESPSomfy-RTS UI.  

So, I went to each shade and added another remote by pressing a burr on on the Telis 4 while it is in the group mode.  So now, each shade shows two remotes in ESPSomfy-RTS, one for the individual shad/remote button nd one for the group shade/remote button.  As a result, the shade status in the UI is correct whether I use the individual or group mode on the Telis remote.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/65464558/447c3641-58bf-473b-8738-d1eb0a7eae8d)

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/65464558/41aecfc3-cfa3-4db6-8ab0-1490b4b4c42a)

In the image above you can see a common remote number for each shade. This is the group mode from the Telis remote.

Hope this is helpful and not a duplicate.

**Comment by rstrouse** [comment]
Yep that is the correct way to link the grouped channel from your remote.  When I get some time I have some documentation updates (additions) to do.   I'll do better to indicate how to set up a grouped channel.

**Comment by rstrouse** [comment]
I added some additional instructions to the Wiki.

https://github.com/rstrouse/ESPSomfy-RTS/wiki/Configuring-the-Software#linking-remotes
