### ISSUE TITLE
Rolling codes seem to be getting out of sync.

### ISSUE THREAD

**Issue by plaurien** [rstrouse/ESPSomfy-RTS#260]
### Hardware

ESP32

### Firmware version

v2.3.2

### Application version

v2.3.2

### What happened? What did you expect to happen?

Hello - very nice work on the project!

Yesterday I did install this project on an ESP32 and also integrated it with my HACS; very intuitive.
Following the guide, I paired my shutters and controls but it seems something is going off track… I’m under the impression using the remotes or the RTS Integration gets the rolling codes out of sync.

For example, I need to click multiple times to open (or close) a shutter before it reacts. As of that moment, any 1-time action is working fine. If I then switch to my original remote control, same thing happens; I have to press the button 10-15 times before the shutter reacts. Further actions on the original control work fine. Then back to RTS, I have again that big offset of sequence. (looking at the radio logs, I can find the original remote sequence but not the one from the RTS itself as it’s not logged)

Did I do anything wrong with my setup? I’ve tried to re-initialize and re-learn two shutters completely (disconnecting them, setting the original control as day-0, setting the higher/lower limits aso…) but nothing seems to help.

Also have to mention I have the 5-groups remote controls that were in use but I did not use them at all…

Thank you in advance for your help!
Pierre

### How to reproduce it (setp by step)

```bash
1. Go to...
2. Click on...
...
```

**Comment by plaurien** [comment]
Ha..... me sometimes very idiotic :-D
In the address, I was using the shutter address that was sniffed and by reading the manual again, I realized it's an unique address for the ESP... (RTFM).

Will not delete my post in case someone as lazy as myself runs into the same issue.... jeez :-D

**Comment by rstrouse** [comment]
These are the symptoms you will experience if you used the same address as the remote for the shade definitions in ESPSomfy RTS.  If these are the same change the address in the software and pair it.

**Comment by plaurien** [comment]
Thanks a lot for your reply. I have worked around that and finally got it to work :)
I did not realize I had to delete the shutter and re-add it to change the address.
It's all working like a charm now, thanks a lot for your help and project!!!
