### ISSUE TITLE
Send move to my position by mqtt

### ISSUE THREAD

**Issue by christoph-ng** [rstrouse/ESPSomfy-RTS#263]
### Hardware

ESP32

### Firmware version

2.3.3

### Application version

2.3.3

### What happened? What did you expect to happen?

I want to send the move to "my" position by mqtt, but by sending 0 to espsomfy/shades/7/direction/set i can stop the shades, but not send him to my position.

### How to reproduce it (setp by step)

```bash
send 0 to topic espsomfy/shades/7/direction/set
```

**Comment by rstrouse** [comment]
@christoph-ng if you are still having issues re-open this ticket and provide some additional details.  I tested this on several devices and it works correctly.
