### ISSUE TITLE
ESPSomfy-RTS losing track of blind if "Step Up" is sent after "Down" or "Step Down" after "Up"

### ISSUE THREAD

**Issue by perfrankling** [rstrouse/ESPSomfy-RTS#275]
### Hardware

Olimex ESP32-PoE/EVB

### Firmware version

v2.3.3

### Application version

v2.3.3

### What happened? What did you expect to happen?

I have a Somfy blind with tilt. If I send (from the virtual remote or from HA) a "Down" command followed by "Step Up", the blind stops, but the ESPSomfy-RTS thinks that it continues travelling down all the way to fully closed. The same happens when sending an "Up" command followd by "Step Down". The blind stops, but ESPSomfy reports that it keeps moving all the way to fully open.

### How to reproduce it (step by step)

```bash
1. Press Down on the virtual remote
2. Press "Step Up" on the virtual remote

or

1. Press Up on the virtual remote
2. Press "Step Down" on the virtual remote
```

**Comment by rstrouse** [comment]
Do you have this set to 80 bits?

**Comment by perfrankling** [comment]
> Do you have this set to 80 bits?

Yes. The same thing happens if I set it to 56 bit (tested that as well now).

**Comment by perfrankling** [comment]
> The same thing happens if I set it to 56 bit (tested that as well now).

Sorry, incorrect. If I change the settings for the blind to 56 bits, the "StepUp" and "StepDown" commands have no effect.

**Comment by rstrouse** [comment]
It needs to be set to 80 bits for the step up/down to work.  I do not have a blind with this capability.  So it sending a step command stops all movement if the blind is in motion?

**Comment by rstrouse** [comment]
@011V32 has this been your experience with this as well?  Just checking to see if there are differences with functionality on the motors.

**Comment by perfrankling** [comment]
Could it ever make sense that the movement continues after a step command?

The tracking of the movement is correct if the step command is in the same direction as the preceding Up/Down command. In that case ESPSomfy-RTS correctly understands that the movement has stopped.

**Comment by rstrouse** [comment]
Does it track correctly if you are using a tilt wheel on a remote?  Is this only when using the virtual remote?

**Comment by rstrouse** [comment]
Install the v2.4.0 pre-release and see if the issue is solved for you.

**Comment by perfrankling** [comment]
> Does it track correctly if you are using a tilt wheel on a remote? Is this only when using the virtual remote?

It is the same behaviour with the physical remote with tilt wheel, with the virtual remote, and when controlled from HA.

**Comment by perfrankling** [comment]
> Install the v2.4.0 pre-release and see if the issue is solved for you.

Yes, seems completely solved now! Thanks for this - and especially for turning it around so quickly!

**Comment by 011V32** [comment]
> @011V32 has this been your experience with this as well? Just checking to see if there are differences with functionality on the motors.

I've never tested this case because I would always end it with a Stop/My command...
I'm still traveling at the moment and couldn't test it until the evening, if that's still relevant?
