### ISSUE TITLE
Stumbled over SLZB-06: might this be used for ESPSomfy-RTS?

### ISSUE THREAD

**Issue by fft1010** [rstrouse/ESPSomfy-RTS#288]
Hi,
I just stumbled over https://smlight.tech/product/slzb-06/ and wonder how are chances, that I could use this for ESPSomfy-RTS hardware instead of the things, that I did.

IMHO it might be much more accepted by the management :-) here in my house.

It has an ESP32 but I cannot judge, if the RTS sending part can be fulfilled with the hardware.

thanks
Juergen

**Comment by rstrouse** [comment]
Those are zigbee.  Your motors would need to be zigbee motors not RTS.

**Comment by fft1010** [comment]
Hi @rstrouse,
yes, I have seen it, but my idea is to flash this with your software. It has an ESP32, it has a WLAN and it has a 2.4MHz sender. As far as I understood Zigbee is "only" the protocol. I "just" wanted to use the hardware.

Any chance?

thanks
Juergen

**Comment by rstrouse** [comment]
Here are some pics of my latest creation with a tiny ESP32-S3 and a 58x35x15mm enclosure from Amazon.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/6c4dc73a-712c-4268-88b9-1a0084d4730a)
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/f965845e-f289-4eff-9781-a087ca738bb6)

**Comment by rstrouse** [comment]
@fft1010 that device will not work as the radio is not capable of producing the sub-ghz signals required.

**Comment by rstrouse** [comment]
I am going to close this for now.
