### ISSUE TITLE
Control other RF Blinds

### ISSUE THREAD

**Issue by jbrandek** [rstrouse/ESPSomfy-RTS#292]
### Describe you new feature you'd like

It colud be possible to extend this project for normal RF Blinds? it is really complicate to set a normal RF blind in ESP, you need to cipher the code to copy it and reproduce the RAW code after... and the way it calculate the position is really bad, this project would be the solution for many users that have non Somfy blinds
It wold be nice to make it as easy as is to add a somfy blind for any RF motorized blinds

**Comment by jbrandek** [comment]
> What is meant by a 'normal' RF blind? It may be difficult to determine without a precise specification due to the numerous radio protocols available. Additionally, the frequency range presents a unique challenge as Somfy operates on 433.42 MHz, which differs from the more common 433.92 MHz used by other 433 MHz applications. This makes the parallel operation of Somfy and other radio receivers a particular challenge...

Oh no i dont mean to control both at same time, i just mean use this easy and nice gui way to also config other blinds, remote controled rf blinds.
To make it easy to copy the rf signal from the remote and make it as a time based covers, just to make it user friendly asi it is right now for somfy, maybe the user can set up the frecuancy as the specs of the remote and then make it a easier way to configure than the code based esphome that you have to cipher the whole dump to see what to use of the raw data...

**Comment by rstrouse** [comment]
Did you know that many of the 433.92 motors are actually already supported by changing the base frequency to 433.92 then using the RTW or RTV protocol?  However, the transceiver can only be set to one base frequency and it must conform to either a 56 bit or 80 bit transmission packet.   Not all motors conform to this.

**Comment by jbrandek** [comment]
No i didnt ok i will try that, thanks, i tried to read a remote signal,  setting the frecuency at 433.92 but didnt work, but i will try again to see if i can make it work

**Comment by rstrouse** [comment]
I am closing this for now and assume you got this sorted.
