### ISSUE TITLE
[Feature request] Zigbee support 

### ISSUE THREAD

**Issue by meiser79** [rstrouse/ESPSomfy-RTS#303]
### Describe you new feature you'd like

Hi,

I'd be very interested to use your project with a Zigbee based ESP32 which connects to HA via Zigbee2MQTT. I just read about the [ePulse Feather C6](https://thingpulse.com/product/epulse-feather-low-power-esp32-c6/) which sounds very interesting.

May I ask if this might be feasible?

Thanks in advance,
meiser

**Comment by rstrouse** [comment]
I am going to close this for now.
