### ISSUE TITLE
Show IP address on website

### ISSUE THREAD

**Issue by 011V32** [rstrouse/ESPSomfy-RTS#310]
### Describe you new feature you'd like

It would be great if the IP address could be displayed somewhere on the website.
Thanks.

**Comment by rstrouse** [comment]
On the DHCP/Static IP tab if you temporarily uncheck the Acquire IP Address automatically checkbox the current IP address is placed in the Static IP field.

**Comment by rstrouse** [comment]
I published 2.4.1 and the IP address is now prominently displayed on the DHCP tab.

**Comment by 011V32** [comment]
I couldn't see it. Even if I uncheck the DHCP option. 🙃
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/22346481/f6cbc1d2-0dd1-4d86-b2cc-230a45722f03)
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/22346481/20d219cd-24c6-4e3d-9c15-51fc76a8da5a)

**Comment by rstrouse** [comment]
I am not sure how that could be possible.  Please clear your browser cache.

**Comment by 011V32** [comment]
I tried. The InPrivate window didn't help either. Neither on the Mac, nor on the PC or cell phone & tablet... 😞

**Comment by rstrouse** [comment]
Are you seeing any errors in the browser console?

**Comment by Jumperm** [comment]
Today I want to check the browser console in Chrome and today is the first day I see the IP. In Safari (macOS/iOS), chrome ... curious!

**Comment by rstrouse** [comment]
Most likely, the cache expired for the client files in the browser.

**Comment by 011V32** [comment]
Where I have to look?
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/22346481/0fb57e7a-010d-4cc6-ae6c-1a325a5e59c0)

**Comment by rstrouse** [comment]
That I didn’t expect it looks like the Ethernet library isn’t returning a current ip address.

**Comment by rstrouse** [comment]
If you install the v2.4.2 pre-release I believe I found the cause of this.   As it turns out the IP address sometimes does not get assigned until after the uplink reports connected.
