### ISSUE TITLE
Lost all config after an update

### ISSUE THREAD

**Issue by Nickduino** [rstrouse/ESPSomfy-RTS#313]
### Hardware

ESP32-C3

### Firmware version

v2.4.1

### Application version

v2.4.1

### What happened? What did you expect to happen?

I lost all my rooms and shades after the update. I expected them to be restored.

I'm an idiot, I should have done a manual backup but I was on the Home Assistant app, not my PC, so...

### How to reproduce it (step by step)

```bash
1. Open Home Assistant settings
2. Click "see all updates"
3. Select ESPSomfy RTS firmware and update
4. Once updated, see that there are no blinds and no rooms in your ESPSomfy RTS install
```

**Comment by Nickduino** [comment]
> I'm an idiot, I should have done a manual backup but I was on the Home Assistant app, not my PC, so...

I thought I had an older one but I can't find it.
**"Create backup" was ticked on the Home Assistant dialog box. Did HA do a backup of my shades? How can I access it?**

**Comment by Nickduino** [comment]
I read the other similar issues but I don't have a backup file to try and restore the shades

>  **Did HA do a backup of my shades? How can I access it?**

I'm a HA noob, should the backup be here?
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/9784237/f30ac909-6ba8-45df-a38c-c1fa584a8bca)

Or is there a different backup directory for HACS?

**Comment by rstrouse** [comment]
Yes the backup is in the `config/ESPSomfyRTS_XXXXXX` where Xs = the chip id.

**Comment by rstrouse** [comment]
You can use the file editor in HA to download this file.  If you click the folder icon you will see the directory

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/dc9caa5a-7d45-4210-8df0-76f85415c281)

**Comment by Nickduino** [comment]
> Yes the backup is in the `config/ESPSomfyRTS_XXXXXX` where Xs = the chip id.

> You can use the file editor in HA to download this file. If you click the folder icon you will see the directory

Thanks! I restored all shades, rooms and groups :-)

Maybe you could mention the HA backup folder somewhere (like on the firmware tab of the GUI)?

**Comment by rstrouse** [comment]
> Maybe you could mention the HA backup folder somewhere (like on the firmware tab of the GUI)?

Eventually I am going to add a UI to HA to allow you to list and restore a backup file.  In the meantime that is not such a bad idea.
