### ISSUE TITLE
Unable to establish initial network ESP Somfy RTS

### ISSUE THREAD

**Issue by Findu28** [rstrouse/ESPSomfy-RTS#320]
### Hardware

ESP32

### Firmware version

v2.4.1

### Application version

v2.4.1

### What happened? What did you expect to happen?

I tried several different ESP32 (S3, C, ..), but none is able to bring up the initial network.
When i try the "Prepare for first use", all of them work fine.

### How to reproduce it (step by step)

```bash
1. Firmware programming - works fine.
2. Initial network - not shown
```

### Logs

```bash
...
```

**Comment by rstrouse** [comment]
If the ESP32 is not booting into AP mode then please review whether you missed any steps from the wiki.  You must download the SomfyController.onboard.esp32xx.bin.zip file from the release and extract the file inside.   Then use that file to flash the board.

**Comment by Findu28** [comment]
Thanks.
After several reprogrammings it now works.

-----Ursprüngliche Nachricht-----
Von: rstrouse ***@***.***> 
Gesendet: Sonntag, 7. April 2024 17:50
An: rstrouse/ESPSomfy-RTS ***@***.***>
Cc: Wolfgang A. ***@***.***>; Author ***@***.***>
Betreff: Re: [rstrouse/ESPSomfy-RTS] Unable to establish initial network ESP Somfy RTS (Issue #320)

If the ESP32 is not booting into AP mode then please review whether you missed any steps from the wiki. You must download the SomfyController.onboard.esp32xx.bin.zip file from the release and extract the file inside. Then use that file to flash the board.

**Comment by rstrouse** [comment]
Awesome!  Glad you got it working.
