### ISSUE TITLE
500: Service error

### ISSUE THREAD

**Issue by Nickduino** [rstrouse/ESPSomfy-RTS#321]
### Hardware

ESP32-C3

### Firmware version

v2.4.1

### Application version

v2.4.1

### What happened? What did you expect to happen?

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/9784237/0a20b3b7-a889-4926-8d27-0fd75787a126)

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/9784237/ebc8d21a-2eba-45a6-ad57-75a8a93a2b3a)

This is relatively common (something like once a week) but I don't know what triggers it. Are you aware of that issue?

### How to reproduce it (step by step)

```bash
1. Open Home Assistant, notice the shutter buttons aren't clickable;
2. reload the device in http://homeassistant.local:8123/config/integrations/integration/espsomfy_rts, notice it's stuck at "Initializing";
3. open the ESP32's own GUI and get the screenshots posted or an ERR_CONNECTION_TIMED_OUT (or a DNS_PROBE_FINISHED_NXDOMAIN if trying to use the mDNS)
```

**Comment by rstrouse** [comment]
The mDNS for ESP32 is not great in that I don’t think it sends the appropriate packets for .local resolution when the network reserves the domain.   There could be something I am missing with it but it is supposed to be a couple of lines of code.

Essentially the gateway loses the reference.  Using the ip address bypasses the name resolution and adding an ip reservation on the router that includes the hostname also fixes it.

**Comment by Nickduino** [comment]
I get the same errors when I connect to it with the IP address.

I mentioned the mDNS only because the message changes slightly when the connection to the device is completely impossible.

**Comment by rstrouse** [comment]
I added some additional TCP publishing on the v2.4.2 pre-release.  Let's see where that takes us.

**Comment by rstrouse** [comment]
@Nickduino have you seen an improvement with this issue after installing v2.4.2 pre-release?

**Comment by rstrouse** [comment]
@Nickduino please make sure you update to the official v2.4.2 release.  There have been many improvements on the final release.

**Comment by Nickduino** [comment]
Done. 

I haven't had any issue with the pre-release, though.
