### ISSUE TITLE
NanoCUL support?

### ISSUE THREAD

**Issue by jmau2002** [rstrouse/ESPSomfy-RTS#33]
I have a NanoCUL stick, 433MHz, C1101, ATMEGA328P .
https://www.smart-home-komponente.de/nano-cul/nano-cul-433-extern/#cc-m-product-8485093976

Is it possible to flash the firmware on it?

**Comment by rstrouse** [comment]
I do not believe so.  The software was developed for the ESP32 but you can certainly try to port it, but it will likely require rework given the architecture differences for the ATMEGA.

**Comment by rstrouse** [comment]
I am closing this for now as I don't have any plans to port to the ATMEGA chip.
