### ISSUE TITLE
Is there a way to go back into AP mode?

### ISSUE THREAD

**Issue by AAfetisov** [rstrouse/ESPSomfy-RTS#333]
### Describe you new feature you'd like

In case wifi credentials has changed

**Comment by rstrouse** [comment]
It should automatically drop back to AP mode after trying for a bit to connect.

**Comment by AAfetisov** [comment]
> It should automatically drop back to AP mode after trying for a bit to connect.
will it continue to try connecting nonetheless? Because what if there are problems with wifi or it was temporary switched off

**Comment by rstrouse** [comment]
If it cannot find the SSID or it cannot connect it will switch on the AP and it should appear in your network list.  In both of your above conditions the AP mode should be turned on.   If no clients connect to the AP after 3 minutes it will try the original SSID again.  If that fails it will re-open the AP and wait another 3 minutes until it gets a connection.

**Comment by AAfetisov** [comment]
> If it cannot find the SSID or it cannot connect it will switch on the AP and it should appear in your network list. In both of your above conditions the AP mode should be turned on. If no clients connect to the AP after 3 minutes it will try the original SSID again. If that fails it will re-open the AP and wait another 3 minutes until it gets a connection.

Only after asking that question I kinda realised I could check it myself :) The algorithm is great, thank you :) It made AP and then reconnected to wifi on it's own. Really great. I just have ptsd from my meross socket which makes me dive behind sofa at my office once a week to replug it because it stops it's reconnection attempts(weak wifi there)

**Comment by rstrouse** [comment]
Glad you got it sorted so I am going to close this for now.
