### ISSUE TITLE
Unable to find any signal when scanning frequencies

### ISSUE THREAD

**Issue by Chaospilot1980** [rstrouse/ESPSomfy-RTS#340]
### Hardware

ESP32

### Firmware version

v2.4.1

### Application version

v2.4.1

### What happened? What did you expect to happen?

I got everything running, initailizing the radio is done. But i cant find any signals at all. tried 4 different remotes, but the radio does not pcik up anything. not in logfilæes, not upon scan frequencies.

Wiring is:
Radio Module - color - ESP32 board
1/GND - Grey - GND
2/VCC - Purple - 3,3
3/GDO0TX - Blue - 13
4/CSN - Green - 05
5/SCLK - Yellow - 18
6/MOSI - Orange - 23
7/MISO - Red - 19
8/GDO2RX - Brown - 12

![20240421_205630](https://github.com/rstrouse/ESPSomfy-RTS/assets/94291741/ba7c412b-4f77-4ee2-b9be-f8ed39084cbc)
![20240421_205535](https://github.com/rstrouse/ESPSomfy-RTS/assets/94291741/1fcd46a9-6f12-4ee0-96a1-7740a1bc4b95)
![20240421_205543](https://github.com/rstrouse/ESPSomfy-RTS/assets/94291741/b3489f51-57bc-4db1-a71d-f86a74f2a647)
![20240421_205554](https://github.com/rstrouse/ESPSomfy-RTS/assets/94291741/4c22d70e-5de7-4f9d-b9bc-1669cca268a1)
![20240421_205620](https://github.com/rstrouse/ESPSomfy-RTS/assets/94291741/072b773e-6ffc-4485-bd78-4c7457935368)
![20240417_150354](https://github.com/rstrouse/ESPSomfy-RTS/assets/94291741/7737365f-3d29-4881-b5f2-83b3ffd009c1)
![20240417_150543](https://github.com/rstrouse/ESPSomfy-RTS/assets/94291741/347a308a-2ae8-4762-801d-30028a2ad2e0)
![20240420_222851](https://github.com/rstrouse/ESPSomfy-RTS/assets/94291741/75881ef3-697a-401c-9046-d659c3292a80)
![71k3Qw8yTqL _AC_SL1500_](https://github.com/rstrouse/ESPSomfy-RTS/assets/94291741/3d3e180b-4d6d-4992-ae0c-a3ff18c550a1)
![71Jr8yBLq7L _AC_SL1500_](https://github.com/rstrouse/ESPSomfy-RTS/assets/94291741/fcd8aea2-9f2d-4635-8e2d-0810a872a6dd)

### How to reproduce it (step by step)

```bash
1. Go to...
2. Click on...
...
```

**Comment by rstrouse** [comment]
Ok I have determined that your wiring is correct if your radio pin settings look like this.
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/b312dc1a-3fb2-4717-a6da-f4a2464b5502)

Just to be sure your remotes do not say IO on them anywhere when your read the back of it.   The led on RTS remotes will most often be red in color when you press a button on the remote.  The radio for IO HomeControl is fundamentally different and will not work with this solution.  This only works with RTS.

If that is the case verify that you also have 433.42mhz selected.

**Comment by rstrouse** [comment]
@Chaospilot1980 did you get your issue resolved?

**Comment by rstrouse** [comment]
@Chaospilot1980 I am going to close this for now.  Feel free to reopen if you want to continue to troubleshoot.
