### ISSUE TITLE
First tries

### ISSUE THREAD

**Issue by gralfj** [rstrouse/ESPSomfy-RTS#346]
Hi there, just finished building a device and want to share my experience with you, and thank the creator of the project.

Well, i am totally new to microsoldering, though i consider myself a geek, so, i decided to start this project cause I am in the process of making my home domotic.

I have several blinds remote controller as well some more controlled by hardwired wall switches, primary goal is to control the remote controlled ones blinds vía voice.

I bought all the required for a mini controller hardware at AliExpress. When all the stuff arrived I felt a bit overwhelmed heheheheheneheh. Well I soldered pins tomthe esp device in order to connect It to the antena with wires and came up with this

![IMG_20240425_100041](https://github.com/rstrouse/ESPSomfy-RTS/assets/166150610/e9ccc699-acd4-4fc2-8f3e-45cfa3341605)

Have to say that after flashing the firm and connectimg my tablet to the esp wifi, tachan!!!!! Everything worked as espected.

Well, i followed the wiki steps and found that the scan button never ffound ant available wifi, even though the device IS besides the main router, so i wrote the ssid down along with the password, and set Up a static ip, and hit the save adapter button wich never poped up the the warning screen.

![250648730-9635678c-e0ed-4df3-b1bd-08f6ec2811f2](https://github.com/rstrouse/ESPSomfy-RTS/assets/166150610/7f5dca23-0c22-4766-afaf-dff73d29d9ec)

This confused me, though didn't stopped me, so I tried to reboot the device and _voila_ there It was.

 So, again,  thank you for your project and now I Will be testimg It Deep and come back with questions. Have to say that every remote controlled blind is configured and working nice.

One thing I have found IS that the HA repository isn't available at HACS, IS there any issue with that?

**Comment by rstrouse** [comment]
No magic smoke is a great sign that weak solder skills are not in your way ;)

To get the repository in HACs click the custom repository menu from the upper right of the HACs store then enter https://github.com/ESPSomfy-RTS-HA into the url then add the integration. Once you are done doing that restart HA and your device should be discovered.

**Comment by gralfj** [comment]
Sorry i am not english fluent, i think that i understand the refrain, but , please, explain it to me.

Ill try the integration ASAP

Thanks in advance.

**Comment by gralfj** [comment]
> when you do get adventurous with a solder iron check out my S3 build. https://github.com/rstrouse/ESPSomfy-RTS/wiki/Mini-ESP32s3-Device-Build

that´s the hardware I bought, but I found it easy, in first place, to communicate each bug with wires, but I am willing to solder a mini too.

by the way adding the custom repository does not work for me

**Comment by rstrouse** [comment]
Do you have HACS installed on your HA?   If you do open it from the HA menus.  Then click the three dots menu in the upper right of the screen and choose Custom Repositories.

When the dialog opens enter the url below in the repository field and choose integration as the category.  Then click add.
https://github.com/rstrouse/ESPSomfy-RTS-HA

You should now download ESPSomfy RTS.

**Comment by gralfj** [comment]
Yes, i have and it does not work, button does nothing. I have aldo tried
manually, same result

**Comment by rstrouse** [comment]
Which button does not work?

**Comment by gralfj** [comment]
Add repo

![Screenshot_2024-04-27-17-53-59-402_com android chrome](https://github.com/rstrouse/ESPSomfy-RTS/assets/166150610/3b8351c6-7395-4131-b01f-c5ef029e7808)

**Comment by gralfj** [comment]
Fixed! From mobile device add button worked

**Comment by rstrouse** [comment]
Awesome glad you are up and running!

**Comment by gralfj** [comment]
Great!
