### ISSUE TITLE
Homekit plugin picture

### ISSUE THREAD

**Issue by AragornSRB** [rstrouse/ESPSomfy-RTS#362]
Can someone share picture how this plugin looks in Homekit?Im using Hombridge-rpi-rts plugin and works ok but in homekit looks like switch.Is this one different?

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/76788550/c372e99e-e688-4695-bc30-f44e290f3515)

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/76788550/63efbfb8-ba9e-4a19-ac6b-71fe6ace1709)

**Comment by rstrouse** [comment]
For me they show up as a cover entity.

**Comment by rstrouse** [comment]
@AragornSRB I suspect that this is driven by the entity type so if it is a blind, shade, or shutter, it will show up as a a cover.  If it is a garage door then it will show up as a garage door.  And if it is a gate it will show up as a gate.   All of those include the current position of the entity.

It will never show up as a switch unless you define it as a dry contact.  ESPSomfy RTS fills in the proper entity classes in the plugin and I suspect the other plugin does not.
