### ISSUE TITLE
ESP32 C3 GPIO List

### ISSUE THREAD

**Issue by HeinKlocktein** [rstrouse/ESPSomfy-RTS#367]
### Hardware

ESP32-C3

### Firmware version

v2.4.3

### Application version

v2.4.3

### What happened? What did you expect to happen?

Ther are not all gpios visible. 
Hope that these picture are helpfull: 
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/61840781/42c02261-6bba-46f0-9c5d-179323d3804f)
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/61840781/81cd2f30-7169-42bb-b560-b62625e4f3b8)
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/61840781/1a33fbcc-a683-4525-900c-0919a80d343d)
It would be helpfull to get an GPIO recommendation like you did for the WROOM32
I have tried several GPIOS without success.
 

### How to reproduce it (step by step)

```bash
Radio menu, open the transiver tab. 
Open the SCLK dropdown and compare it with the other dropdown for the GPIO configuration .
Compare it with wroom32 and the attached C3 Pinout
```

**Comment by rstrouse** [comment]
I do not have this board layout my C3 mini is from Seeed Studios.   So lets start with those pins you cannot use as they are dedicated to other things.  It is very odd that nearly half of the pins on this board are dedicated to power and ground.

***Pins that I would avoid:***
Strapping pins: GPIO2, GPIO10, GPIO9, GPIO10
USB pins: GPIO18, GPIO19
External clock pins: GPIO0, GPIO1 -- These I really don't know the implication of using them for anything other than an external clock.  

SCK = GPIO6
CSN = GPIO7
MOSI = GPIO3
MISO = GPIO5
RX/TX = GPIO4  -- I would only hook up the GDO0 pin on the transceiver and let ESPSomfy RTS multiplex on this pin.  I see this board has a CH340 chip on it and I suspect that they wired that to GPIO20 and GPIO21, 

Really I am a bit puzzled by the strange design of this board.  For my Seeed board there are actually more usable pins with only 14 pins exposed on a smaller platform.  Clearly this was made for some specific purpose.

***For the Seeed I used***
SCK = GPIO5
CSN = GPIO6
MOSI = GPIO10
MISO = GPIO9
RX = GPIO6
TX = GPIO7

**Comment by HeinKlocktein** [comment]
Your recommendation works well:  
SCK = GPIO6
CSN = GPIO7
MOSI = GPIO3
MISO = GPIO5
RX/TX = GPIO4
Thank you very much!
