### ISSUE TITLE
Blinds operating together

### ISSUE THREAD

**Issue by nsleigh** [rstrouse/ESPSomfy-RTS#372]
### Hardware

ESP32

### Firmware version

v2.4.3

### Application version

v2.4.3

### What happened? What did you expect to happen?

I have 2 blinds in different rooms, when I operate blind 1 then blind 2 also operates, if I operate blind 2 it works on its own. Both seem to have separate ID's and the remotes for each are paired with the appropriate blind and ESPSomfyRTS setting.

Any idea what would cause this and how to fix it?

### How to reproduce it (step by step)

```bash
Press up or down on blind 1 and both operate
Press up or down on blind 2 and blind 2 operates
```

**Comment by rstrouse** [comment]
Open the memory on blind 2 by long pressing the prog button on a remote that ONLY controls that motor.   Then press the prog button on the ESPSomfy RTS shade you want to unpair.  You can use the virtual remote for that.
