### ISSUE TITLE
The module is not working

### ISSUE THREAD

**Issue by Jeff2405** [rstrouse/ESPSomfy-RTS#373]
### Hardware

ESP32-C3

### Firmware version

v2.4.3

### Application version

v2.4.3

### What happened? What did you expect to happen?

hello I just bought an ESP32C3 mini with an SMA CC1101.I configured as follows and it doesn't work. My remote control is a somfy T4300.
![Sans titre](https://github.com/rstrouse/ESPSomfy-RTS/assets/104680887/0d644693-e0be-4b01-8e3e-9f178eba8d44)
![20240515_210734](https://github.com/rstrouse/ESPSomfy-RTS/assets/104680887/4f27a446-ae2f-4e2e-af17-f3aa00ee0718)
![20240515_210805](https://github.com/rstrouse/ESPSomfy-RTS/assets/104680887/51b1df5b-8710-40f5-900d-953937beee39)
![20240515_210722](https://github.com/rstrouse/ESPSomfy-RTS/assets/104680887/4da017f1-e50a-44c8-a1cb-7034151a5055)
![20240515_210815](https://github.com/rstrouse/ESPSomfy-RTS/assets/104680887/6531251a-419b-4472-b000-7d9b413329ce)

### How to reproduce it (step by step)

```bash
1. Go to...
2. Click on...
...
```

**Comment by rstrouse** [comment]
Take a picture of the front and back of your remote.

**Comment by Jeff2405** [comment]
![20240516_071519](https://github.com/rstrouse/ESPSomfy-RTS/assets/104680887/90572b91-1594-48f2-a254-bbf4fd6a0190)
![Uploading 20240516_071526.jpg…]()

**Comment by Jeff2405** [comment]
![Uploading 20240516_071526.jpg…]()

**Comment by rstrouse** [comment]
Ok I know that is a 73400 not a T3400.

Do you have a picture of the pinout for that board?  Is it this?
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/91656ca7-21e3-4d0c-8692-841af794c377)

Also can you take a better picture of the CC1101 connections?

**Comment by Jeff2405** [comment]
![image_2024-05-17_111725922](https://github.com/rstrouse/ESPSomfy-RTS/assets/104680887/2b02b8a1-eee5-4c06-ab5c-8b7c6ff22d56)

**Comment by Jeff2405** [comment]
![image_2024-05-17_111936224](https://github.com/rstrouse/ESPSomfy-RTS/assets/104680887/ec7c4814-5ca5-4058-a425-d6bed8fc9471)

**Comment by rstrouse** [comment]
I cannot see which pins you have connected to the CC1101.  Take a picture of the CC1101 were I can see the connector and the orientation of the board.

**Comment by rstrouse** [comment]
> If this ESP card doesn't work, which one should I get?

Honestly I love the Xiao ESP32S3.  I did a build with it and the S3 chip is blazingly fast with everything.  It is very small and the Wifi is spectacular.

https://github.com/rstrouse/ESPSomfy-RTS/wiki/Mini-ESP32s3-Device-Build

As an aside when you are testing I assume you have an antenna screwed into the connector on the transceiver.  Is that correct?

**Comment by Jeff2405** [comment]
yes I have a connected antenna

**Comment by rstrouse** [comment]
Now that I have the pics I will double check your wiring but I suspect that it is correct.  I am so used to folks not wiring correctly.

There is another user with this board having issues and I see reports online that the edge interrupts do not work correctly on it.  However, I have another version of the C3 where it does work correctly but there are similar reports online for it.

https://github.com/rstrouse/ESPSomfy-RTS/issues/353

One think to note is that the C series chips use a RISC-V architecture that may simply be harder for the board suppliers to get right.

**Comment by rstrouse** [comment]
Here is what I see on your wiring is this correct?

| Tr Pin | Color | Func | ESP32 |
| --- | --- | --- | --- |
| 1 | Black | GND | GND |
| 2 | Red | 3v3 | 3v3 |
| 3 | White | GDO0/TX | GPIO9 |
| 4 | Brown | CSN | GPIO7 |
| 5 | Gold | SCLK | GPIO4 |
| 6 | Gray | MOSI | GPIO6 |
| 7 | Yellow | MISO | GPIO5 |
| 8 | Orange | GDO2/RX | GPIO10 |

If it is try (without changing any wiring) changing the RX and TX setting to GPIO9 in the configuration then press Save Radio. Then see if you get any frames from the remote.

**Comment by Jeff2405** [comment]
It still doesn't work even when reversing

**Comment by Jeff2405** [comment]
I took this file
![Capture d'écran 2024-05-17 212125](https://github.com/rstrouse/ESPSomfy-RTS/assets/104680887/e9599865-1540-413a-aaff-d5a6f5ba40c9)

**Comment by rstrouse** [comment]
For a C3 that is the correct file.  I don't want you to reverse it I want you to set the TX and the RX settings to GPIO9 and hook that up to Pin3 on the transceiver.

**Comment by Jeff2405** [comment]
I link RX and TX together??

**Comment by rstrouse** [comment]
You can ignore the GDO2 connection.  ESPSomfy RTS will multiplex on GDO0.

**Comment by Jeff2405** [comment]
I now have the radio not initialized

**Comment by Jeff2405** [comment]
it's good the radio I put on RX GPIO 09 and ela still doesn't work

**Comment by rstrouse** [comment]
Did the radio not initialized message go away with that configuration where you have GPIO9 for RX/TX?

**Comment by Jeff2405** [comment]
no it was a wire that was unplugged

**Comment by Jeff2405** [comment]
it s ok thank you

**Comment by rstrouse** [comment]
Are you up and running or are you still having problems?

**Comment by Jeff2405** [comment]
yes it works I think it's a soldering problem on the esp

**Comment by rstrouse** [comment]
Awesome closing this!
