### ISSUE TITLE
Docker port

### ISSUE THREAD

**Issue by cook1emr** [rstrouse/ESPSomfy-RTS#374]
Has anyone looked at porting this firmware over to docker? These USB C1011 dongle maybe good hardware to allow this.
https://a.aliexpress.com/_Ex9a4yj

**Comment by rstrouse** [comment]
I am pretty sure that would take a bit more than just porting the firmware to docker.   ESPSomfy RTS communicates with the transceiver over SPI and not over RS232.  There would need to be some driver work done to bitbang on RS232.  In the end you would be back to an MCU.

I guess what I am saying is that it is possible but I don't see a need for it.

**Comment by cook1emr** [comment]
Thank you for the response, I truly appreciate it.

In terms of use case I think projects like zigbee2mqtt or zwavejs are good examples. Being able to attach radios to a single machine runing a docker stack acting as a hub can offer simplicity and flexibility.

Would this SPI project be useful to create a USB to spi bridge https://pypi.org/project/spi-adapter/

**Comment by rstrouse** [comment]
I am going to close this as I don't plan to create a docker port.
