### ISSUE TITLE
adding the IO control point 

### ISSUE THREAD

**Issue by customshell** [rstrouse/ESPSomfy-RTS#375]
If it is possible to add io integration with 868 mhz frequency ... 

https://github.com/Velocet/iown-homecontrol

Something like that

**Comment by rstrouse** [comment]
Unfortunately, that is a task I am not willing to take on.  If others would like to make that work feel free to use anything in this project to get there.  I don't own and never will own an IO controlled anything.

**Comment by customshell** [comment]
okay then , thanks for answer.
