### ISSUE TITLE
WIFI AP

### ISSUE THREAD

**Issue by goanes** [rstrouse/ESPSomfy-RTS#380]
### Describe you new feature you'd like

Hi
I look arround and did not found a way to disable the wifi AP.
Is that possible ?
Thanks for this great job bth.

**Comment by rstrouse** [comment]
As soon as you successfully connect with WiFi or wired connection and reboot it will disable the AP and only enable it if it cannot connect.  It needs to do this so that it does not brick if you simply change your connection credentials.

**Comment by goanes** [comment]
Ok I Will  double check that.
On an other project, they disable the AP after a configured time period (e.g. 5min)
And if we need AP, we just need to reboot the esp.
Thanks for your quick answer
