### ISSUE TITLE
Question: support hardware "Connair" (foto inside) possible?

### ISSUE THREAD

**Issue by c1328** [rstrouse/ESPSomfy-RTS#389]
### Describe you new feature you'd like

Hi all,

at first I want to say thanks to that project - I have it running smoothly for some weeks and it works quite nice.

I remembered I used a project called "Connair" a few years ago:
Device: https://www.amazon.de/ConnAir-433-Home-Automation-Gateway/product-reviews/B008W1G620
Project page: I'll try to find it....

My question is, if this device can anyhow used with this somfy project - I know it's not a ESP32 but maybe someone has an idea. Here is a foto:
![IMG_5719](https://github.com/rstrouse/ESPSomfy-RTS/assets/112856305/d3110251-b3f0-45f8-895a-dc966c1f05a7)

Thanks and regards
Carl

**Comment by rstrouse** [comment]
This will not work with ESPSomfy RTS.  That processor is not supported.

**Comment by rstrouse** [comment]
I am going to close this as I don't plan on supporting this hardware.
