### ISSUE TITLE
Add a second (alternative) Wi-FI to connect to, when the primary is not available

### ISSUE THREAD

**Issue by qntris** [rstrouse/ESPSomfy-RTS#394]
### Describe you new feature you'd like

Just as in Tasmota, it would be great to have the option to add a second WiFi ssid and password. That way, one could set up the module and do the initial validation at their lab/home and then complete the shade setup at the desired location.

**Comment by rstrouse** [comment]
You can still perform that operation without a second SSID.  When the configured SSID does not exist, it will open the the SoftAP mode.  At which time you can set the credentials for the final destination.

While the multi ap settings that are used in Tasmota may seem like a good idea they cause the scan to have to look for more APs.  This is problematic when supporting roaming.
