### ISSUE TITLE
Possibility to link more than one remote with different frequencies

### ISSUE THREAD

**Issue by Jpm100P2** [rstrouse/ESPSomfy-RTS#399]
### Describe you new feature you'd like

In my use case I've 3 remote Somfy Telis 1 RTS Pure controllers that drives 3 different awnings. 
I successfully paired all three awning and everything works as expected.

Next step, linking the remotes...

I successfully linked 2 of 3 because it seems that they're on the same frequency but I can't link the third one unless I change its frequency, but in this case i loose the first two.

I'd like to have the possibility to manage multiple remotes.

**Comment by rstrouse** [comment]
Increase the rx bandwidth. It sounds like the 3rd remote is probably not well tuned.

**Comment by Jezza34000** [comment]
You have to set the frequency in the middle of all your remote.  
+ as @rstrouse  says increase bandwidth it will solve your problem

**Comment by rstrouse** [comment]
@Jpm100P2 did making the changes described above fix your issues?  Also, if you have not changed the batteries in the remotes in a while this would be a good opportunity to do so.

**Comment by Jpm100P2** [comment]
Hi, yesterday I did the suggestion of @Jezza34000  including your suggestion and it worked. 
Many thanks.

**Comment by rstrouse** [comment]
Cool I am closing this.  If you have any other issues please submit a new issue.
