### ISSUE TITLE
Questions 1870917 KEYPAD 2 RTS

### ISSUE THREAD

**Issue by PGLDK** [rstrouse/ESPSomfy-RTS#405]
### Describe you new feature you'd like

Hi. Simple question. With this excellent work of art. Would it be poesible to add KEYPAD 2 RTS to Home Assistant this Way? Just looking for a sollution to pair button two to Home Assistant to use the keypads second Channel controlling non-somfy devices.

**Comment by rstrouse** [comment]
Yes ESPSomfy RTS supports both 1 button and 2 button dry contact controls.

**Comment by rstrouse** [comment]
I am going to close this for now.  If you have issues getting the motors to pair open another issue and we will work through it.
