### ISSUE TITLE
Ability to Override Current Position

### ISSUE THREAD

**Issue by BillyFKidney** [rstrouse/ESPSomfy-RTS#415]
### Describe you new feature you'd like

The signal from our wind sensor is very weak and often not received by ESPSomfy despite relocating the antenna (10 dBi).
In order to recognize the awning is no longer extended I have a ZigBee contact (door) sensor attached to the arms.

When ESPSomfy reports the awning to be extended, but the contact sensor has been closed for 30s, Home Assistant will issue the close command correcting ESPSomfy's position. 

If I could force set the position it would be far less cumbersome.

**Comment by rstrouse** [comment]
There are services to set the target position as well as the current position in the ESPSomfy services for HA.  This is the Change Position service.

**Comment by BillyFKidney** [comment]
<img width="1115" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/4c79b342-185e-43b5-9f55-168265a3775e">

The services send a command to the motor, but I want to update ESPSomfy because the position is wrong. 

<img width="897" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/e0aae675-7d13-4659-b1b3-9615a7ee4ec7">

ESPSomfy believes the awning is open but in reality it is closed. 

<img width="553" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/e125c18c-d3d7-407a-a60e-db0361b166b1">

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/b0e26ec4-4fdf-4a1a-b532-c559408a0b47)

**Comment by rstrouse** [comment]
Do not use the Set Position service use Change Position

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/f5374b46-0719-425c-8ab8-e40c1ad88d1f)

**Comment by rstrouse** [comment]
@BillyFKidney did you figure out how to set the position with the service above?

**Comment by BillyFKidney** [comment]
> Do not use the Set Position service use Change Position
> 
> ![image](https://private-user-images.githubusercontent.com/47839015/343421824-f5374b46-0719-425c-8ab8-e40c1ad88d1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMjgyMDEsIm5iZiI6MTcyMDEyNzkwMSwicGF0aCI6Ii80NzgzOTAxNS8zNDM0MjE4MjQtZjUzNzRiNDYtMDcxOS00MjVjLThhYjgtZTQwYzFhZDg4ZDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDIxMTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YWQwODk0ZDI3YWZlNjdiNmQwZDViMzUxMmU3ZDdjM2M0MmNlOWYwYTRhNWU2NDNjZDhjMDk4ZTE0M2JjODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rI2W7ZTESkY8zFKElSCFqYx5fF1y23W_ol5nxAb6gIs)

Thanks, I was not using Home Assistant's Developer Tools so I missed the additional information.


<img width="708" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/65253277/6b6ceff3-5b14-4a6b-a405-67c39fcf6c22">
