### ISSUE TITLE
Blind positions are incorrect, used to be OK

### ISSUE THREAD

**Issue by FlaMike** [rstrouse/ESPSomfy-RTS#42]
I have 8 roller shades controlled with ESPSomfy RTS and integrated with HA using the HACS integration.  When I set up the system, I timed the open & close times, added & paired the shades & linked the remotes.

I don't know when or how it happened, but I noticed this morning that 6 of the 8 shades do not show the correct position in HA or on the ESPSomfy RTS web interface.  It appears HA and the web interface are in agreement with the "incorrect" positions, however.

Can you please let me know how to correct the reported blind positions?  Do I need to delete & re-add the shades & remotes?

Attached is a screenshot of the web interface.  All of the blinds are currently open 100%, but only the Master_BR_West and Casita shades reflect the position correctly.

I was running 1.4.6 but updated a few minutes ago to 1.5.3.  I am running HACS integration 1.0.12.

Thanks for your help!

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/41341956/073148cc-839b-49ec-88a3-85fa7611f536)

**Comment by rstrouse** [comment]
No don't delete anything just press the up button on the ones that are out of sync in the ESPSomfyRTS interface and wait for them to finish.  Then update to v1.5.3

**Comment by FlaMike** [comment]
And Home Assistant now shows all of the shades as "open."  I'm going to close this issue to save you the hassle.

Thanks & have a super day!
