### ISSUE TITLE
Errror show on main page

### ISSUE THREAD

**Issue by ionutm80** [rstrouse/ESPSomfy-RTS#420]
### Hardware

ESP32-S3

### Firmware version

v2.4.5

### Application version

v2.4.5

### What happened? What did you expect to happen?

Hi, I have 2 errors shown on the main page, see print screen attached.
1. One show an exclamation mark in a red triangle for one of the blinds although it works perfectly.
2. One show that the 2nd blind has a sun sensor although I do not have such a thing.
![IMG_4899](https://github.com/rstrouse/ESPSomfy-RTS/assets/68031938/2706d325-6a5c-4beb-a500-fcd4a59840e9)

![IMG_4896](https://github.com/rstrouse/ESPSomfy-RTS/assets/68031938/7b11a4e9-4cb0-4828-9c57-38b924ed6d91)
![IMG_4895](https://github.com/rstrouse/ESPSomfy-RTS/assets/68031938/c80bab49-9760-4951-baf8-918b75709433)

### How to reproduce it (step by step)

```bash
1. Go to main page where each blind is shown.
```

### Logs

```bash
No line present in the log section.
```

**Comment by rstrouse** [comment]
That is not an error.  You have two indicators from a Sun/Wind sensor.  The triangle is for the wind and the little sun is for the sun.

If you have these indicators erroneously on your display and you do not have a sensor, then you likely triggered these on the virtual remote page. To clear them send a sensor command from the virtual remote without any of the checkboxes checked.

**Comment by ionutm80** [comment]
Yesit worked! Yeay!!! Thanks!
