### ISSUE TITLE
Problems with installing the Firmware

### ISSUE THREAD

**Issue by d3bu9** [rstrouse/ESPSomfy-RTS#43]
Hello I tried to Install the Firmware but the ESP keeps restarting every second.
I tried Firmware 1.5.3 and 1.5.0 on a ESP8266 D1 and on ESP32C3.
I also tried over ESPHome and with the ESP Tool.
I guess this is a beginners Problem, can anyone help me with this?

**Comment by rstrouse** [comment]
I do not have a C3 but I suspect that the RISC-V version of the chip is not compiled for the firmware.  I attempted to recompile the firmware with this chip series but ran into problems with the floating point math libraries.  Your best bet is to get one of the S models.

**Comment by d3bu9** [comment]
Is it possible to alternatively install the ESP Home Firmware first (that works on Both my Devices ESP8266 and ESP32C3), and then laod one of your Firmware Files via OTA Update?

![Bildschirmfoto 2023-05-09 um 22 01 41](https://github.com/rstrouse/ESPSomfy-RTS/assets/44096168/e14f6cb0-bafc-407e-bcd3-34df27375361)

**Comment by rstrouse** [comment]
I am guessing you will run into some of the same library differences that I did when trying to compile for the chip.

**Comment by d3bu9** [comment]
Thanks for your Help and the great work on that Project. I gave up two years ago, so now I'm happy that I can use your Version - just need a decent ESP.

**Comment by rstrouse** [comment]
Lots of folks have been having great success!
