### ISSUE TITLE
Adding  EST-PoE-32 - ESP32 PoE Development Kit

### ISSUE THREAD

**Issue by moshiko2312** [rstrouse/ESPSomfy-RTS#436]
Hi
can you  please  add this board  to the Lan GPIO and add tables for GPIO Board, i checking all works  good. 👍 
Thanks  for your  job  its amazing .

https://shop.everythingsmart.io/products/est-poe-32-esp32-poe-development-board

![EST-PoE-32GPIOPinout4k](https://github.com/user-attachments/assets/883648a0-ac6d-491e-97b8-a8c85c945adb)

![Lan_Gpio](https://github.com/user-attachments/assets/b7651e78-64e3-4688-ad7e-b6375cf93bd5)
![gpio](https://github.com/user-attachments/assets/6a0e0438-4002-4a7f-a243-457479ab1fe6)

<img width="481" alt="image" src="https://github.com/user-attachments/assets/f06f7d9a-703f-422a-9f63-23cf1e6bd38d">

<img width="792" alt="image" src="https://github.com/user-attachments/assets/fb1d4f18-2f00-4f0f-a122-ac294d9607a2">

**Comment by rstrouse** [comment]
Thanks, I will add the settings and the docs.

**Comment by rstrouse** [comment]
Done v2.4.6 released.
