### ISSUE TITLE
Tuple Index out of range?

### ISSUE THREAD

**Issue by Pleeriezer** [rstrouse/ESPSomfy-RTS#450]
### Hardware

ESP32

### Firmware version

2.4.3

### Application version

2.4.2

### What happened? What did you expect to happen?

Hello,

I get a message in HA that there is a new version of he software.
Tried to install it but I am getting te message Tuple Index out of range.
And I can not install it?

How can I install the latest version?

### How to reproduce it (step by step)

```bash
1. Go to...
2. Click on...
...
```

### Logs

```bash
No log available
```

**Comment by rstrouse** [comment]
Unfortunately, HA did an update that made breaking changes that have been fixed in v2.4.7 of the HA plugin.  If you are using HACS simply go to the HACS store in HA and select ESPSomfy RTS.  On the upper right you will see a 3 dot menu.  Click on redownload and install v2.4.7,

**Comment by Pleeriezer** [comment]
Thanks for the quick reply.

Unfortunately I see no espsomfy in my HACS?

![somfy3](https://github.com/user-attachments/assets/a922a7ac-e52d-4c4a-9295-3c38229a27ef)

**Comment by rstrouse** [comment]
Did you install it from HACS or did you copy the files to the custom_components directory manually?

**Comment by Pleeriezer** [comment]
I installed it a few years ago trough HACS?

**Comment by rstrouse** [comment]
Hmmm.... when you select the filter to Downloaded on the right and clear the search text does HACS show up?  I am running 1.34.  Also do you have an espsomfy_rts directory in the homeassistant/custom_components/ directory?

**Comment by Pleeriezer** [comment]
Yes I have :

![hacsd](https://github.com/user-attachments/assets/0e1d3ed1-4710-4b40-8072-a5ae1faca834)

![hacse](https://github.com/user-attachments/assets/80eee08f-24ac-4a4f-96fa-bf30bde488aa)

![hacsf](https://github.com/user-attachments/assets/5d7d40a1-55ed-4e95-8351-ebebe00ed8b1)

**Comment by Pleeriezer** [comment]
Hello,

I have updated it trough Github, so I hope that in the future it will be good.
Thnx for the help!
