### ISSUE TITLE
Venetian blind moves independently

### ISSUE THREAD

**Issue by 011V32** [rstrouse/ESPSomfy-RTS#465]
### Hardware

LilyGO T-Internet POE

### Firmware version

v2.4.6

### Application version

v2.4.6

### What happened? What did you expect to happen?

I don't know why, but today one of our venetian blinds simply closed itself step by step.
In HomeAssistant I can see that it wasn't done by anything else, but by the module itself.
Can you find out what the problem was?
<img width="261" alt="Bildschirmfoto 2024-09-02 um 18 17 52" src="https://github.com/user-attachments/assets/0e7dddc5-8d08-4698-9d5e-5c6dc2b41d53">
<img width="451" alt="Bildschirmfoto 2024-09-02 um 18 20 38" src="https://github.com/user-attachments/assets/9d33bd48-1233-4ef6-9c4f-824931f85ec3">

### How to reproduce it (step by step)

```bash
Unfortunately, I can't say. The system has been online for many weeks and this is the first time it has done this...
```

**Comment by rstrouse** [comment]
There really isn’t anything that would trigger this in ESPSomfy RTS unless it is requested to do so from some other source.  Are you sure there is nothing setting the position over the rest api.

**Comment by 011V32** [comment]
I only use HomeAssistant in conjunction with this device. My family then uses the device via HomeKit, which is provided by HomeAssistant. So directly or another device such as HomeAssistant does not connect to ESPSomfy-RTS. The commands were not executed by HomeAssistant, as you can see from the log. When I then restarted the device, this phenomenon stopped again. I can see whether it occurs again in a few weeks...

What is perhaps worth mentioning is that the device only took steps. So no movement and then stopped again, but the command for a single step.

**Comment by rstrouse** [comment]
HA does not really execute any commands.  However, it is capable of sending a rest request to execute the command to ESPSomfy RTS.   Are you sure that it is sending a STEP command?   You can see this in the Last cmd attribute for the entity as well as the source of the command.  If you have a wheel that is spitting these out it should tell you which remote is doing it.  Bear in mind that ESPSomfy RTS does not issue STEP commands unless it is told to do so externally.   All control from the device will be UP/DOWN/MY commands to move the motor from the interface but it will hear those commands and adjust the position accordingly.

**Comment by 011V32** [comment]
If the command is executed with HomeAssistant, it says with which integration etc. it was executed by. Only if it is not executed by/through HomeAssistant, as in the image above, nothing is said. Since I didn't see anything in the logs, I assume that it was executed by ESPSomfy-RTS.
But since it doesn't occur again after the restart, I can't diagnose it at the moment.
What should I look out for or what should I do if it happens again?
Thanks.

**Comment by 011V32** [comment]
Since it hasn't happened again so far, I'm going to close it for now.
If it happens again, I'll reopen it.
