### ISSUE TITLE
Sun and warning icon?

### ISSUE THREAD

**Issue by XilviuX** [rstrouse/ESPSomfy-RTS#466]
### Hardware

Other

### Firmware version

v.2.4.6

### Application version

v.2.4.6

### What happened? What did you expect to happen?

I'm trying to follow the Somfy instructions to fine-tune the higher and lower end position of the curtain. I can't seem to make this work, but during the different tests I saw that the web interface displays these icons. What is their meaning?
<img width="513" alt="Screenshot 2024-09-02 at 19 47 43" src="https://github.com/user-attachments/assets/85b610b3-e8e6-4bfe-8cc1-154977f5f799">

### How to reproduce it (step by step)

```bash
1. follow instructions from Somfy to adjust the high and low positions (which don't work for my curtain anyway, yay), that is: hold up and down together for 5 seconds, adjust the position, and press "my" for 2 seconds.
2. the icons appears in the interface
```

**Comment by rstrouse** [comment]
Please go to the virtual remote, select the motor from the drop-down and send a sensor command to the motor.  That will clear the sunny and windy sensor settings.

**Comment by XilviuX** [comment]
Just tried it and it didn't change anything. I also tried setting, then unsetting the checkboxes at the bottom of the virtual remote page (sunny and windy sensors) and this worked - the icons are gone. Thanks for the tip.
