### ISSUE TITLE
All shades gone after update to fw v2.4.6

### ISSUE THREAD

**Issue by rgr101** [rstrouse/ESPSomfy-RTS#468]
### Hardware

ESP32

### Firmware version

v2.4.6

### Application version

v2.4.6

### What happened? What did you expect to happen?

After having updated from HA to firmware v2.4.6 all my shades were gone (Fortunately, all other properties remained). 

Unfortunately, I neglected to make a manual backup before the update, not least because I relied on the activated option in HA of doing an automatic backup. But after the update I couldn't find a backup file anywhere; I would have expected HA to create an HA-internal backup being listed there?

Anyway - I was lucky that I found an about 3 months old backup and succeeded in estimating the approximate increase in the rolling codes and patching them manually! All the shades miraculously work again 😅!

but... 

... Why have been the shades gone? 
... Why did the backup in HA not work?

### How to reproduce it (step by step)

```bash
1. Go to...
2. Click on...
...
```

**Comment by rstrouse** [comment]
The backup is located in the config directory in your home Assistant.   It performs this backup prior to installing the firmware.   If there is any interruption when downloading and installing the file system then you will need the backup.

**Comment by rgr101** [comment]
ah I see- thx! Have found it. I thought it would show up in HA's system->backup section 😇
