### ISSUE TITLE
Change WiFi SSID -or- force access point? 

### ISSUE THREAD

**Issue by nicoodeimos** [rstrouse/ESPSomfy-RTS#474]
### Describe you new feature you'd like

Hello there, I'm sorry if this has already been answered before, but I couldn't find any reference to this.
Basically, if I want to change the configured SSID before my Wifi name has changed, is there any way to return to access point mode to be able to change settings?
Many thanks!

**Comment by rstrouse** [comment]
You can go into the network tab and remove the SSID then press save.

**Comment by nicoodeimos** [comment]
But what if the esp device is unjoinable? (for ex. I move into a new house with a new SSID, and the ESP doesn't know the new environment because it is still looking for old wifi credentials).
Is there any way to put the esp in access point mode again to setup a new SSID/password?

**Comment by rstrouse** [comment]
It will automatically fall back to the Soft AP mode if it cannot find the SSID after 20 seconds.

**Comment by nicoodeimos** [comment]
Awesome ok, thank you so much!
