### ISSUE TITLE
Can pair Somfy shades, but they are not moving

### ISSUE THREAD

**Issue by Bleala** [rstrouse/ESPSomfy-RTS#489]
### Hardware

ESP32

### Firmware version

v2.4.6

### Application version

v2.4.6

### What happened? What did you expect to happen?

Hello!

I'm currently trying ESPSomfy and it's pretty cool, way better than my current solution with Rfxtrx.

I'm having about 25 shades in my house, all are the normal Somfy RTS.

I was able to pair every shade and all are working correctly expect two.

These two shades do not move, when I press up/down in the ESPSomy UI, every other shade is working correctly.

These two also pair normally. I press the prog button on my remote, then I press the prog button in the web UI and I can see/hear that the shade jogs.

I tried repairing the two shades a few times, because I thought this could solve the problem, but it didn't (I always removed the shade correctly from the UI before with unpair und waited, that the shade jogs).

Is there any known bug/solution?

Greetings

### How to reproduce it (step by step)

```bash
1. Pair shade
2. Try to move it from the UI
```

**Comment by rstrouse** [comment]
Keep in mind that if the shade is paired already it will unpair if you pair it again.   Pairing and unpairing are the same command to the motor.   The other thing that may be plaguing you is that some motors go to sleep after each command.  In this instance you should add some repeats to the command which you can do from the UI.  What this does is allow a sleepy motor to wake up and actually hear the command.   It is near impossible to get a single frame when using the remote as you will need to press the button for less than 1/10th of a second for a single frame.

Also, some motors actually jog as if the pairing is successful even though it has run out of pairing slots.   In that instance you may need to factory reset these two which clears out all the previously paired addresses and makes room for ESPSomfy RTS.  Somfy recommends the reset procedure in their remote pairing instructions for this very reason.

**Comment by Bleala** [comment]
Thanks for your reply!

I ended up to factory reset these two shades, looked like the motor was no able to save more "remotes".

Now every shade is working as expected :) 

Greetings
