### ISSUE TITLE
Set up multiple channels on ESPSomfyRTS using a single channel remote

### ISSUE THREAD

**Issue by wjschmitt** [rstrouse/ESPSomfy-RTS#490]
Currently I have a single channel Telis remote and two shade motors.  The remote is set up to operate both motors.  When I press the Prog button on the remote, both motors jog.  I set up ESPSomfyRTS to pair as a single shade that operates both motors.  I want to set up  two separate shades plus a group.  The instructions seem to indicate that this is possible (or at least, not impossible), but I don't know what pairing steps to follow to make this happen.

First of all, is this possible?  If so, how would I do it?

Should I reset the motors, then pair one at a time, and then pair the group, on both the remote and in the app?  Or can I keep the pairing that I have, but add new pairings for each motor separately by cutting power to the other motor?

Or should I just give up and buy a Telis 4 remote?

**Comment by rstrouse** [comment]
You have the right idea killing power to the motor you do not want to include the pairing for.  When a motor does not have power it will not be able to open its memory and accept a new address.   This should work beautifully.

**Comment by wjschmitt** [comment]
Ok, this worked brilliantly.  I paired each shade separately by powering one at a time, then added each to the group.  I now have a multi-channel virtual remote without needing a real one.  This software is excellent.  Thanks for your work on this.  Well done.
