### ISSUE TITLE
Wrong Somfy Sonesse 40 RTS positioning

### ISSUE THREAD

**Issue by nikbyte** [rstrouse/ESPSomfy-RTS#496]
### Hardware

ESP32 WT32-ETH01

### Firmware version

v.2.4.7

### Application version

v.2.4.7

### What happened? What did you expect to happen?

Hello!

Please help me to understand what's wrong.
I have a blind based on Somfy Sonesse 40 RTS motor.

I paired it with ESPSomfy-RTS without any issues.
When I set position 0%, it opens completely (expected behaviour, all ok).
When I set position 100%, ot closes completely (this is also expected behaviour).

However when I want to set it to 50%, for example, it closes for about 25%.
When I set it to 99%, it closes for about 50%.

I.e. I can close it completely, but I can't close it, for example, to 80 or 90% because by real it's for about 35-40%.

How to fix this behaviour?

### How to reproduce it (step by step)

```bash
1. Go to web application (or home assistant integration)
2. Set position to 0 - it opens it, result ok.
3. Set position to 100 - it closes it, result ok.
4. Set position to 50 - here is an issue. Expected behaviour 50%, real behaviour 25%.
```

**Comment by rstrouse** [comment]
You have not properly set the up/down timing on your motors.  Please set this timing and the positioning will be correct.

https://github.com/rstrouse/ESPSomfy-RTS/wiki/Configuring-the-Software#motor-timing

**Comment by nikbyte** [comment]
Thank you! This is what I completely missed.
