### ISSUE TITLE
Shade pairing doesn't work

### ISSUE THREAD

**Issue by skupu** [rstrouse/ESPSomfy-RTS#50]
Hi @rstrouse,

I have problem with pairing the Somfy Altus RTS shades - I can see the commands in log, so the CC1101 works fine, I can link the remote, but unfortunately the pairing procedure gives no result.

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/10194143/a2348d9d-586c-4bec-9c19-c5d8425888c7)
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/10194143/d7528bf0-b65d-4e04-95ec-905385d9be8e)

Please support.

**Comment by rstrouse** [comment]
Change TX to GPIO-13 and RX to GPIO-12 then hit save.  Do not rewire just change the two values in the screen above.  GDO0 must be wired to TX.  You can receive on either pin but can only send on GDO0.

**Comment by skupu** [comment]
Thanks. I replaced ESP to wroom (before I used ESPDUINO and none of the pins were working - I tried some of them).

Now the pairing works, but the shades are not moving...

Any idea?

**Comment by rstrouse** [comment]
Somfy pairing can be really dumb.  You may be trying to pair and the shade mystically jogs but what it is actually doing is unpairing.  The other thing is that motors only have a certain number of slots so it will jog but not store the address.  Somfy recommends resetting to factory settings.

**Comment by skupu** [comment]
I just did with one of the 5 shades I have. Now I only have one telis paired, cannot pair the other that worked (somehow it went unpaired) and I don't know why still the ESPSomfy doesn't work

**Comment by skupu** [comment]
I tried with another shade and hapily it started working - both remotes are ok and the RTSomfy works well.
So I will try with the rest and post results. Possibly I will make another factory reset of the not working one tomorrow afternoon.

**Comment by getselim-stack** [comment]
> Change TX to GPIO-13 and RX to GPIO-12 then hit save. Do not rewire just change the two values in the screen above. GDO0 must be wired to TX. You can receive on either pin but can only send on GDO0.

I made the same mistake - thanks!

**Comment by rstrouse** [comment]
I am closing this as I assume everybody has everything working whether it is related to ESPSomfy RTS or not.  If you need further assistance open another issue.
