### ISSUE TITLE
Fix for certain roller blinds - send unique packets for repeats, rather than the exact same packet

### ISSUE THREAD

**Issue by LukeT92** [rstrouse/ESPSomfy-RTS#510]
Hi,

I'm currently on firmware v2.4.3. I have the "Repeat Commands" field set to 3 to improve the responsiveness of my window coverings, however this isn't compatible with one of my roller blinds. The blind sees repeat packets with the same rolling code as a user holding the up or down arrow buttons on the remote. This means the blind moves until you release the button. However, with the ESPSomfy, it means the blind only moves a tiny amount, then stops.

I ended up hacking the SomfyRemote::sendCommand(...) function in Somfy.cpp, putting in an outer loop that sends 3 unique packets for this specific blind, rather than 3 copies of the same packet, (I hooked a repeat count of 20 as an easy way to trigger this). This has entirely fixed the problem and has made operation of that blind reliable.

Is this something that has been added to newer firmware versions? If not, I'd love to see this as a full feature. Probably a tickbox on the shade config page to indicate that repeat packets should have unique rolling codes.

I've attached a git diff of the hack I made for reference.
[Somfy.cpp.diff.txt](https://github.com/user-attachments/files/18185905/Somfy.cpp.diff.txt)

Cheers,
Luke

**Comment by rstrouse** [comment]
Are you sure this motor is not set to Tilt mode?   This sounds very much like that and it can be toggled on the motor.  Most of them are toggled by moving the motor away from its endstops.  Then press and hold the UP and DOWN button until the motor jogs.   Then press and hold the MY and DOWN button until it jogs again.

**Comment by LukeT92** [comment]
Aha, that was it! I had no idea they could be swapped between modes like that. Clearly the installer left it in the wrong mode. Thanks for your help.
Btw, this is an awesome project :)
