### ISSUE TITLE
A Valid Shade ID not Supplied

### ISSUE THREAD

**Issue by nobbyneb** [rstrouse/ESPSomfy-RTS#52]
Strangely, a number of additional shades were created in addition to the original Shade i had setup (Garage at the top). Not sure how this happened. On trying to delete, i get the error 'A Avalid Shade ID not Supplied'. I have tried editing the name and parameters of these but continue to get the same error. Thanks!

![Screenshot 2023-05-21 at 13 25 46](https://github.com/rstrouse/ESPSomfy-RTS/assets/5697598/ee85d00e-f695-42ae-87dd-25f5eca44718)
![Screenshot 2023-05-21 at 13 25 38](https://github.com/rstrouse/ESPSomfy-RTS/assets/5697598/d6e443e5-48b0-4e75-b3cf-14698e93bdf5)

**Comment by rstrouse** [comment]
Go to the updates tab and create a backup.  Then post that here.

**Comment by nobbyneb** [comment]
Thank you, attached.

[ESPSomfyRTS 2023-05-21T20_26_22.backup.zip](https://github.com/rstrouse/ESPSomfy-RTS/files/11525364/ESPSomfyRTS.2023-05-21T20_26_22.backup.zip)

**Comment by rstrouse** [comment]
I do not understand what went on with that but it looks like it wrote a corrupted configuration.  Anyhow if you only had one shade configured, under the gears option go to updates and restore this file after you extract it.
[ESPSomfyRTS 2023-05-21T20_26_22.zip](https://github.com/rstrouse/ESPSomfy-RTS/files/11525425/ESPSomfyRTS.2023-05-21T20_26_22.zip)

Any insight into what you were doing when the corruption occurred?

**Comment by nobbyneb** [comment]
Very kind of you, thank you - the backup worked perfectly.

It was very strange. I was fumbling around with the loose ESP and Radio module (must have been while they were still powered). The corrupted config then appeared when i next logged in, i can only think i shorted or misconnected some pins somehow. Really appreciate the help.

**Comment by rstrouse** [comment]
That would do it.  Let me know if you need anything else.
