### ISSUE TITLE
Does not Work if MQTT Broker is offline/crashed

### ISSUE THREAD

**Issue by d3bu9** [rstrouse/ESPSomfy-RTS#66]
Wenn my MQTT Broker is not reschsble also the App is not working on Port 80. It says Radio not connected.

**Comment by rstrouse** [comment]
The Radio not Initialized message is not related to MQTT rather this occurs when either the radio is not enabled in the configuration or the wiring to the SPI interface to the radio is not correct which causes the initialization to fail with the driver.

I will set up a broker then disconnect it to see if this makes any difference but I suspect the two are not related.

**Comment by rstrouse** [comment]
I have tried to replicate your scenario and cannot seem to get it to fail.  However, I did clean up some of the code to reset the MQTT connection when there is a change to the configuration.  Please update your device to v1.7.0.

**Comment by d3bu9** [comment]
Just tried it again. As soon as I disconnect my Raspi with the MQTT Broker from the LAN and try to reload the ESPSomfy RTS it shows this:
![grafik](https://github.com/rstrouse/ESPSomfy-RTS/assets/44096168/4e89cc84-193c-4f72-b2c2-ca507ce33e6a)

As soon, as I reattached the LAN to the Raspi, ESPSomy RTS worked again. With disabled MQTT Client this does not happen. I'll do the Update to v1.7.0. an repport again.

**Comment by d3bu9** [comment]
Hmm, the bad news: i just updatet to v1.7.0. And it's the same (eventhough I had to refresh the browser window three times).

Also, I was not able to update the Firmware, I got the folowing error. So I just could update the Application:
![grafik](https://github.com/rstrouse/ESPSomfy-RTS/assets/44096168/b31a5462-e81d-4312-b455-2d80f8882502)



![grafik](https://github.com/rstrouse/ESPSomfy-RTS/assets/44096168/d37ae3f2-dccf-4dfc-89aa-c3a250f71801)

**Comment by rstrouse** [comment]
Hmmm.  That message appears when there are no more available sockets for the webpage.  This can happen if you have too many clients accessing the device at the same time.  Do you have multiple browser windows open to the ESPSomfy web page?

**Comment by rstrouse** [comment]
I am closing this for now.  Let me know if you have any further issues.
