### ISSUE TITLE
Settings icon not working

### ISSUE THREAD

**Issue by Sundancescore** [rstrouse/ESPSomfy-RTS#71]
Hi and thanks for this great project!

I am struggling to configure my shades and got into a problem. The "gear" button in upper-right corner is not clickable and I can not proceed with configuration steps.

<img width="756" alt="settings_not_clickable" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/105753413/ae860a4c-bd10-4e7b-bf59-a7713e79f7b1">

How can I fix this problem?

**Comment by Sundancescore** [comment]
After a few CRTL-F5 the problem was gone, sorry for disturbing you... :)

**Comment by rstrouse** [comment]
No worries.  I'll keep my eye out for a content length mismatch during onboarding the wifi.
