### ISSUE TITLE
Request: Add GPIO33

### ISSUE THREAD

**Issue by Calimerorulez** [rstrouse/ESPSomfy-RTS#73]
Hi, it's me again :)

I'm trying to get an Atom Lite to work with the CC1011, and so far so good. But the config page for the radio is missing any GPIO higher than GPIO31 (only the RX pin has them).

The Atom Lite has a GPIO33 pin. Is it possible to add the higher pins to the dropdown boxes in the GUI?
Thanks!

**Comment by rstrouse** [comment]
Yep I will be releasing v1.7.1 this weekend but have posted the code and binaries and code to the repo already.

**Comment by rstrouse** [comment]
v1.7.1 has been released and contains the additional selections

**Comment by pafnow** [comment]
> Hi, it's me again :)
> 
> I'm trying to get an Atom Lite to work with the CC1011, and so far so good. But the config page for the radio is missing any GPIO higher than GPIO31 (only the RX pin has them).
> 
> The Atom Lite has a GPIO33 pin. Is it possible to add the higher pins to the dropdown boxes in the GUI? Thanks!

Hi, I'm trying to achieve the same, could you share your pin mapping that you used ? TIA

**Comment by Calimerorulez** [comment]
> > Hi, it's me again :)
> > I'm trying to get an Atom Lite to work with the CC1011, and so far so good. But the config page for the radio is missing any GPIO higher than GPIO31 (only the RX pin has them).
> > The Atom Lite has a GPIO33 pin. Is it possible to add the higher pins to the dropdown boxes in the GUI? Thanks!
> 
> Hi, I'm trying to achieve the same, could you share your pin mapping that you used ? TIA

![Image](https://github.com/user-attachments/assets/94bda5df-1309-4ff5-9e39-c478fafacc5c)

I managed it to do without GPIO33 :)

**Comment by pafnow** [comment]
Thanks @Calimerorulez
