### ISSUE TITLE
Issue to pair

### ISSUE THREAD

**Issue by Icare2000** [rstrouse/ESPSomfy-RTS#79]
Hello,

i just installed and crosschecked everthing i could, but i cannot pair the awning. I can have RX from the receiver, but nothing else. I do not understand your remark about: 

"ESPSomfy-RTS device with your motor, then you likely have the RX and TX selections backwards. The CC1101 can only transmit (TX) using the pin marked GDO0 but it can receive on either GDO0 or GDO2."

what should i do.

i have  this hardware

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/11003379/b2f49e32-e26b-4a79-a40e-68fb38ca6e30)

Thanks and best regards

**Comment by rstrouse** [comment]
Go into the configure transceiver screen and swap the values you have recorded for RX and TX.  Then press Save Radio.

**Comment by Icare2000** [comment]
Thanks, this is solved by inverting.... Many thanks for this GREAT job
