### ISSUE TITLE
Documentation / Default settings

### ISSUE THREAD

**Issue by Pulpyyyy** [rstrouse/ESPSomfy-RTS#81]
Hello and thank you for this great tool! I now have my covers always synched.

Regarding documentation, there is an inversion between the default TX/RX values ​​of the documentation/image (GD00/GD02) and the initial default config in  application (GD02/GD00).
So by stupidly following the procedure, we manage to read the frames, but not to pair a new shutter.

**Comment by 011V32** [comment]
I think that's incorrect too, but the help has been revised once before.
Maybe this is a problem of different understanding?

**Comment by Pulpyyyy** [comment]
Maybe it's easier with picture ....
From https://github.com/rstrouse/ESPSomfy-RTS/wiki/Simple-ESPSomfy-RTS-device we have :
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/32004297/53bfa84b-2bdc-4859-9ac8-40e54d0d23e2)
TX is GD00 (pin 13) et RX is GD02 (pin 12)
But from default config (radio page and [doc](https://github.com/rstrouse/ESPSomfy-RTS/wiki/Configuring-the-Software)) 👍 
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/32004297/f9fe1715-160b-4dcc-8db9-b63e06c165b9)
TX is GD02 (pin 12) et RX is GD00 (pin 13)
So obviously reading the doc let's user to correct values, but that' a pitfall

**Comment by rstrouse** [comment]
The defaults have been changed in the next version.

**Comment by rstrouse** [comment]
Version 2.0.0 has been released and the default TX/RX pin mappings have been flipped.
