### ISSUE TITLE
Its possible to add wireless sockets?

### ISSUE THREAD

**Issue by do1kbl** [rstrouse/ESPSomfy-RTS#84]
Hello,
I used this project standAlone without other programms.

But its possible to Add here wireless sockets? or you can make a Copy of this Project for wireless socket?
here one guy modify the RC-Switch lib to used this wireless module
https://github.com/grspy/rcswitch-cc1101

thx

**Comment by rstrouse** [comment]
Sorry, this is way outside of the scope of the software.  The protocol spoken by these is not the RTx versions and this is hardware that I do not posesss.

**Comment by do1kbl** [comment]
Ok thx dir the Info
