### ISSUE TITLE
Unable to pair with Somfy  gate motorization RTS SGA 6000

### ISSUE THREAD

**Issue by ultratoto14** [rstrouse/ESPSomfy-RTS#86]
HI, I have gate motorization from somfy that works for the moment with a RFXtrx433 form rfxcom

The pairing with this gate motization is done by just touching the motorization electronic with the remote and do a short press.
The led should show receive on radio indicator and voila !
I tried that , the led was showing that it receives data but then, subsequent button press does not trigger the motorization.

Can you help me ?

**Comment by rstrouse** [comment]
Are you seeing any frames in the log when you press the buttons on the remote?

**Comment by ultratoto14** [comment]
Yes I can see frames:
```json
[{"encKey": 169,
  "address": 1179905,
  "rcode": 12265,
  "command": "Down",
  "rssi": -43,
  "bits": 56,
  "valid": true,
  "sync": 14,
  "pulses": [2522,2471,2518,2494,2490,2497,2489,2500,2507,2477,2501,2494,2494,2490,4848,1273,1286,1270,1279,1267,1294,634,635,1267,644,650,634,639,630,646,1270,663,634,1277,646,633,634,643,623,644,648,635,1286,621,644,1283,1280,643,630,634,660,614,646,645,629,1290,1275,648,632,640,632,648,643,1277,1259,643,649,1261,653,643,1272,639,632,1270,653,634,1285,644,646,1258,639,643,1274,640,655,1270,1278,641,624,644,649,1260,653,645,1271,639,631,1271,651,636],
  "time": "2023-07-03T14:26:08.553+0200"
},
{"encKey": 169,
  "address": 1179905,
  "rcode": 12265,
  "command": "Down",
  "rssi": -43,
  "bits": 56,
  "valid": true,
  "sync": 14,
  "pulses": [634,32569,2520,2486,2494,2487,2492,2514,2495,2486,2502,2482,2504,2502,2486,2495,4838,1291,1269,1262,1302,1271,1286,620,644,1281,633,645,645,628,634,640,1278,647,653,1266,647,618,650,636,634,654,620,645,1282,641,649,1269,1285,625,643,652,629,635,641,639,648,1258,1290,648,633,639,632,646,643,1279,1258,642,650,1287,626,643,1272,640,655,1271,627,637,1290,644,620,1283,655,620,1294,635,633,1274,1275,660,625,640,649,1259,654,619,1295,639,633,1272,650,636],
  "time": "2023-07-03T14:26:08.696+0200"
},
{"encKey": 169,
  "address": 1179905,
  "rcode": 12265,
  "command": "Down",
  "rssi": -43,
  "bits": 56,
  "valid": true,
  "sync": 14,
  "pulses": [634,32558,2519,2495,2498,2490,2491,2492,2499,2485,2518,2474,2511,2473,2516,2496,4838,1262,1296,1280,1283,1268,1262,641,646,1269,660,615,652,643,647,634,1286,620,645,1280,632,646,644,630,632,634,667,615,1303,613,654,1270,1282,642,649,618,650,635,635,655,619,1295,1260,648,644,628,661,614,654,1269,1280,641,649,1271,633,640,1281,644,628,1288,624,643,1275,639,654,1270,654,613,1285,644,647,1261,1278,645,655,612,658,1276,646,635,1264,646,644,1282,630,625],
  "time": "2023-07-03T14:26:08.841+0200"
},
{"encKey": 170,
  "address": 1179905,
  "rcode": 12266,
  "command": "Down",
  "rssi": -43,
  "bits": 56,
  "valid": true,
  "sync": 14,
  "pulses": [5107,14577,69153,2525,2492,2496,2494,2498,2487,2519,2485,2500,2481,2493,2496,2510,2493,4839,1266,1294,1258,1291,1273,1288,1270,1282,1281,642,626,634,634,1290,648,633,1260,1290,629,659,1264,645,630,1287,651,615,1303,1265,1270,656,640,1256,643,651,1261,1292,648,632,639,631,647,644,1280,1260,643,650,1260,653,645,1273,639,632,1273,650,635,1290,620,647,1278,641,625,1293,634,634,1281,1270,638,659,624,641,1275,659,625,1291,634,635,1266,647,647],
  "time": "2023-07-03T14:27:43.630+0200"
},
{"encKey": 170,
  "address": 1179905,
  "rcode": 12266,
  "command": "Down",
  "rssi": -43,
  "bits": 56,
  "valid": true,
  "sync": 14,
  "pulses": [633,32565,2514,2473,2520,2468,2521,2488,2501,2481,2504,2497,2492,2499,2488,2506,4827,1263,1297,1280,1258,1297,1283,1252,1300,1262,648,642,627,637,1286,643,647,1259,1281,644,628,1290,625,643,1274,640,641,1272,1301,1268,644,622,1282,640,647,1269,1290,626,642,649,637,636,631,1271,1301,616,652,1268,657,638,1283,618,650,1263,652,643,1273,638,656,1270,629,638,1283,644,646,1260,1280,643,628,638,659,1277,620,659,1259,646,643,1281,632,649],
  "time": "2023-07-03T14:27:43.780+0200"
}]
```
This is what is reported when I send commands with my rfxtrx433.

**Comment by rstrouse** [comment]
Swap the settings you have for the RX and TX pin in the Transceiver config.

**Comment by ultratoto14** [comment]
I saw that earlier, I already  checked and switched as my motorization didn't receive anything from ESPSomfy before.
The memorization of the remote is linked to the duration of the button press. It should be less than 500 ms to register a new remote. 
Can you tell me what is the default duration of emitted signal from ESPSomfy ?

**Comment by ultratoto14** [comment]
Just a remark about the switch of configuration for RX/TX, in this [table](https://github.com/rstrouse/ESPSomfy-RTS/wiki/Simple-ESPSomfy-RTS-device#esp-wroom-32esp32s-models), the TX is on GPIO13 and RX on GPIO12 (this is how it is wired for me) but the default value when ESPSomfy-RTS is ran for the first time is the opposite.

**Comment by rstrouse** [comment]
When I publish the pending v2.0.0 release the default will match the table.  

The duration for each initial frame is around 86ms with around 28ms of silence.  So the total time for the prog command is less than 200ms or .2 seconds including the interframe silence.  This command sends an initial frame + 1 repeat.

Below is the output from the pair command.
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/4bfc6d29-fcfd-448d-bdb1-a864fa9e74e8)

**Comment by ultratoto14** [comment]
I gave it to a friend of mine having a real blind. He tested my hardware and it was ok, he can control his blind, the wiring and configuration is good. Just waiting to get it back to do so more tests.

**Comment by rstrouse** [comment]
Is it possible that the memory on the gate controller is full?  Somfy will not pair any more remotes when it gets that way.

**Comment by ultratoto14** [comment]
Hi  @rstrouse, just tested again, and it seems to be linked to the signal power. Usually as mentioned, the key to register need to touch the motor electronic. When I checked it was still not working but I went 50cm away and voilà, it was registered and it works. Really awesome, sorry for the waste of time. 
Now you can add gate in your device list ;-)

**Comment by rstrouse** [comment]
> Now you can add gate in your device list ;-)

And so it seems.  That is now on the enhancement list.
