### ISSUE TITLE
Issue with PUT requests

### ISSUE THREAD

**Issue by prbtt** [rstrouse/ESPSomfy-RTS#87]
I've been trying to develop an app to interact with your firmware, so people that don't use any home automation system could still use this to control their shades easily.

I've noticed that most endpoints if not all get blocked with the CORS error if I send an http PUT request. Is there any other way I can get around this?

**Comment by rstrouse** [comment]
Which endpoints are you using?  The reason I ask is so I can put preflight responses in for your puts.

**Comment by rstrouse** [comment]
v2.0.0 has been released.  Your PUTs should now respond to the preflight request.

**Comment by prbtt** [comment]
> v2.0.0 has been released. Your PUTs should now respond to the preflight request.

Fixed 👏
