### ISSUE TITLE
Question: Control ESPSomfy shades with url?

### ISSUE THREAD

**Issue by do1kbl** [rstrouse/ESPSomfy-RTS#90]
Hello,
its possible to control the shades with url?

for example like this:

ipfromESP32Somfy/Shadename/up
ipfromESP32Somfy/Shadename/my
ipfromESP32Somfy/Shadename/down

**Comment by rstrouse** [comment]
Yes you can call `http://<ip address>/shadeCommand?shadeId=<id>&command=up`

The docs on this are located in the wiki.  To operate the new group commands you use `http://<ip address>/groupCommand?groupId=<id>&command=up`

https://github.com/rstrouse/ESPSomfy-RTS/wiki/Integrations#rest-commands

**Comment by rstrouse** [comment]
I suspect you have this sorted.  I will close this for now.  Open another issue if you have further questions.
